### ISSUE TITLE
SkillEditor需要做一个下拉框，让操作更方便

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#10]
![CGC GQTAD5T)X1Q_AWI3QTU](https://user-images.githubusercontent.com/7448857/119214041-3fcc3200-baf6-11eb-9cac-ffe67c0b8671.png)

如果有时间可以搞点快捷键

**Comment by chenggongchina** [comment]
能够拉下选择 技能名字（自动填入到技能ID）
能够支持下拉选择模型名字（自动填入到模型ID）

**Comment by ly3027929699** [comment]
我来做

**Comment by ly3027929699** [comment]
已上传
