### ISSUE TITLE
Release 上面的macOS 是舊版的build

### ISSUE THREAD

**Issue by Hopefulee** [jynew/jynew#1001]
Always crash when save

**Comment by Hopefulee** [comment]
<img width="2560" alt="Screen Shot 2022-05-06 at 3 06 50 am" src="https://user-images.githubusercontent.com/614350/166975913-4b4ad96a-fd97-455b-a360-c514a2787b66.png">

**Comment by chenggongchina** [comment]
try lastest version?

**Comment by Hopefulee** [comment]
> try lastest version?

I believe it was the latest version.

**Comment by Hopefulee** [comment]
https://pan.baidu.com/s/1sV6yL5z1mdcEDm3wVTKgaA?pwd=jyx2#list/path=%2Fjynew%2FMacOS&parentPath=%2F

**Comment by Hopefulee** [comment]
Okay, I rebuilt the macOS version again with Unity, it seems fine now.

**Comment by XINCGer** [comment]
> Okay, I rebuilt the macOS version again with Unity, it seems fine now.

链接:https://pan.baidu.com/s/1xYn5gkwykHXtcYmTi7TkJg?pwd=cy25 提取码:cy25 
这里的MacOSX平台的包体是新的
