### ISSUE TITLE
wiki : 增加打包帮助相关文档

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#1003]
包括 mono、il2cpp的模式等

**Comment by zhaoqp** [comment]
在线等，谢谢~

**Comment by zhaoqp** [comment]
最新版本的，il2cpp编译没问题了，但是游戏第一关可以进，后面的关卡不知道咋触发

**Comment by Rictong** [comment]
請問那裏可以下載遊戲？

**Comment by zhuziying** [comment]
@Rictong github上下载，最好是早上速度快，还不断
教程在这里 https://github.com/jynew/jynew/wiki/%E5%86%99%E7%BB%99%E6%96%B0%E6%89%8B%E7%9A%84%E9%87%91%E7%BE%A4%E9%87%8D%E5%88%B6%E7%89%88github%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B
