### ISSUE TITLE
lua中的命令未生效

### ISSUE THREAD

**Issue by citydream163** [jynew/jynew#1019]
在ka115.lua中，光明圣火阵开始前，给谢逊等人加血（AddHp）和修改武功的命令（SetOneMagic）未生效。
经测试，AddHp可以给主角和队伍中的角色加血，但无法给其他人加血，比如百花谷的老顽童。
版本号20220429

**Comment by Brown1026** [comment]
想顺便同问要怎么加防御跟医疗，我在Lua加入AddHeal、AddDefence，似乎没有效果，是否可以加入此指令，谢谢。

**Comment by chenggongchina** [comment]
> 

可以仿照AddHp等写法自行编写（因为原版没有这些指令）
