### ISSUE TITLE
渡城残魂传

### ISSUE THREAD

**Issue by LiXuefeng2020ai** [jynew/jynew#1069]
现在是在开发一个新的游戏吗？为什么我git下来进去不是金庸群侠传，二十这个残魂传，而且好像bug很多，经常会卡住

**Comment by ShenFeihua** [comment]
同问

**Comment by MephistoSatanDevil** [comment]
渡城残魂传正在制作中，所以会有很多bug。金群只是渡城残魂传的一个测试MOD，你可以在mod管理中进行切换。

**Comment by qige2016** [comment]
现在应该没啥bug了
