### ISSUE TITLE
关于背包使用按钮的问题

### ISSUE THREAD

**Issue by Juenia** [jynew/jynew#1091]
诸位大佬，不知道能否优化下背包`关闭`和`使用`按钮的问题，`背包页面`的按钮与`选择使用角色页面`的按钮是相反的。
![Screenshot_20220819_204451_com.jynew.jynew.jpg](https://user-images.githubusercontent.com/48351858/185621532-9198ade8-1b28-4f2b-b728-d7e8c42c6815.jpg)
![Screenshot_20220819_204456_com.jynew.jynew.jpg](https://user-images.githubusercontent.com/48351858/185621553-17cc7ff4-624b-46b5-b498-43fb90785947.jpg)

- 可能会造成点击上的不佳体验。

**Comment by qige2016** [comment]
背包按钮应该对调下

**Comment by Juenia** [comment]
> 背包按钮应该对调下

是的
