### ISSUE TITLE
宝箱开启和关闭的实现机制

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#11]
1、资源需要支持，每个宝箱类型做一下骨骼和打开动画
2、代码逻辑实现参考Animancer插件（已传入到工程）

![_PZBOQ0CEJB0Y(PPVJX@18R](https://user-images.githubusercontent.com/7448857/119214077-8ae64500-baf6-11eb-9298-22158cfbeb9f.png)

https://user-images.githubusercontent.com/7448857/119214079-8cb00880-baf6-11eb-8fdf-a6bf5f073b75.mp4

**Comment by chenggongchina** [comment]
补充：宝箱的开启状态需要和存档同步，可以查看GameRuntime宝箱的相关代码。

**Comment by ly3027929699** [comment]
我来做

**Comment by chenggongchina** [comment]
本任务同时包含宝箱的开启/关闭动画实现

**Comment by HYYellowOne** [comment]
宝箱的开启/关闭模型动画已经更新上传

**Comment by chenggongchina** [comment]
似乎还有部分宝箱实现有问题。

**Comment by HYYellowOne** [comment]
5/24 宝箱模型动画更新

**Comment by HYYellowOne** [comment]
5/26 添加Sark1，Sark3，Sark4箱子的打开动画
