### ISSUE TITLE
神龙岛线问题

### ISSUE THREAD

**Issue by sankongjin** [jynew/jynew#113]
神龙岛线问题：
1、喽啰、洪教主没有待机动作
2、洪教主没拿拐杖
3、五毒教喽啰、蓝凤凰没有待机动作
4、五毒教门开了走不进去

**Comment by mapleeit** [comment]
我来尝试解决这个问题

**Comment by mapleeit** [comment]
需要资源：

- [ ] 教主拐杖
- [ ] 小兵的钩子

![MGEBX_`LGH0BZ3L9`AV91O7](https://user-images.githubusercontent.com/4194287/121050599-498ab080-c7eb-11eb-9512-79d6e2988d5d.png)

![)1G~)GB{@6 UE(X6A6$PJ12](https://user-images.githubusercontent.com/4194287/121050647-56a79f80-c7eb-11eb-9081-84e850d492b8.png)

**Comment by qige2016** [comment]
> 神龙岛线问题：
> 1、喽啰、洪教主没有待机动作
> 2、洪教主没拿拐杖
> 3、五毒教喽啰、蓝凤凰没有待机动作
> 4、五毒教门开了走不进去

五毒教门的问题已经修复
