### ISSUE TITLE
换人修炼九阳神功后后续对话都不出来

### ISSUE THREAD

**Issue by daznwng** [jynew/jynew#1137]
如题 ，一开始给张无忌练九阳神功，后来换给主角练，换完之后去灵蛇岛练级，但是对话出出不来了

**Comment by armodeniz** [comment]
这个问题现在是不是已经不存在了？

**Comment by MephistoSatanDevil** [comment]
> 这个问题现在是不是已经不存在了？

之前就未能重现这个问题。应该是什么地方事件卡了。先关了吧。
