### ISSUE TITLE
更新后 阎基居对话卡住

### ISSUE THREAD

**Issue by 0kk470** [jynew/jynew#1170]
### 问题
9.12更新后第一次进入阎基居中毒倒下， 动画结束后在[ka20.lua第15行](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Mods/JYX2/Lua/ka20.lua#L15)的对话
```Talk(4, "原本预备对付苗人凤的悲酥清风，居然先让你受用了！", "talkname4", 0);```处卡住，对话UI不显示了。

### 原因
简单断点看了下，调用对话前会隐藏IntercactUIPanel,  但是这里调整了什么逻辑导致ChatUIPanel层级比IntercactUIPanel高，然后管理Normal层UI的栈将刚打开的ChatUIPanel先弹出隐藏掉了。

![image](https://user-images.githubusercontent.com/25216715/189717024-35dab39b-3541-49bb-92f3-441ac91af1ea.png)

![image](https://user-images.githubusercontent.com/25216715/189717161-168ee754-7140-4989-8883-9849ad738cc5.png)

**Comment by qige2016** [comment]
确认存在此问题

**Comment by 0kk470** [comment]
在停止动画后延迟一小段时间弹出对话后可暂时解决该问题。
![image](https://user-images.githubusercontent.com/25216715/189943682-267586b4-f13d-44cf-aba7-a6732730ed9d.png)

原因是```jyx2_StopTimeline```将玩家控制激活后, [JYX2Player.cs脚本的逻辑循环](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs#L191)下一帧如果判定周围没有可交互的物件会尝试Hide一次InteractPanel。但是ChatUIPanel在当前帧就打开了，所以会先隐藏对话UI。

**Comment by qige2016** [comment]
如果还在jyx2_Wait里面执行了jyx2_StopTimeline就会卡死

**Comment by qige2016** [comment]
目前我暂时把jyx2_StopTimeline执行时机延后，后面想办法解决

**Comment by 0kk470** [comment]
恩，貌似Lua逻辑这边取消掉多线程调用了，逻辑的执行顺序有所变化。
