### ISSUE TITLE
请问这样是可以通关的吗？

### ISSUE THREAD

**Issue by Brown1026** [jynew/jynew#1180]
请问我看渡城残魂传有新增一堆头像图片，
但是有些都没有看到模组，那这样是可以通关的吗，
还是还在製作当中，是否可以先制作人物模组呢，谢谢。

**Comment by citydream163** [comment]
已经在steam正式发布了，怎么会有这种疑问呢？

**Comment by Brown1026** [comment]
我是看这些图片，

![20](https://user-images.githubusercontent.com/102932850/191075673-8c0886e1-08c7-4886-b9f8-5e205fdd79b0.png)

![60](https://user-images.githubusercontent.com/102932850/191075764-cc63e9ae-8e31-42e7-96b1-68395ce2a8f5.png)

![61](https://user-images.githubusercontent.com/102932850/191075796-5ffc5c18-7ee2-4e29-a467-bf5e2ca01023.png)

![70](https://user-images.githubusercontent.com/102932850/191075815-2aadd028-4e63-4642-824f-f2eba4de82e5.png)

可裡头没有看到人物模组，
他还是用原本的金庸群侠传的角色，
所以我才以为还没有制作好，
那这样的话，这些图片的人物，
能够做个模组吗，辛苦製作团队了，谢谢。

**Comment by qige2016** [comment]
https://store.steampowered.com/app/2098790/_/
