### ISSUE TITLE
建议把游戏框架和SAMPLE示例拆分为各自独立的项目

### ISSUE THREAD

**Issue by citydream163** [jynew/jynew#1188]
1.框架项目专注各系统兼容性，各平台的接入，界面操作互动，多语言兼容，UI样式的美化，各种功能的函数实现等平台性的功能；主框架有其专属的版本号。
2.SAMPLE示例独立为渡城残魂传独立MOD开发项目，专注于游戏性的完善以及各种玩法的探究，基础数据的平衡性调整等游戏性功能；渡城残魂传MOD有其专属的版本号。
3.原JYX2的游戏内容独立为金庸群侠传3D重制版MOD开发项目，专注于致敬经典的样本MOD；金庸群侠传3D重制版MOD有其专属的版本号。
4.框架与SAMPLE示例分离的好处：可以在设计函数以及相关功能时更专注于各自侧重点，为后续接入更多兼容MOD打好基础。

**Comment by qige2016** [comment]
后续设计，框架base打包放在streamingassets，sample和jyx2分别打包放在mods内。需要写下工具栏

**Comment by MephistoSatanDevil** [comment]
> 后续设计，框架base打包放在streamingassets，sample和jyx2分别打包放在mods内。需要写下工具栏

我想他说的是直接把MOD独立成单独项目，并且可以脱离平台编译打包的那种。

**Comment by qige2016** [comment]
> > 后续设计，框架base打包放在streamingassets，sample和jyx2分别打包放在mods内。需要写下工具栏
> 
> 我想他说的是直接把MOD独立成单独项目，并且可以脱离平台编译打包的那种。

没必要，现在主流都是monorepo，在版本管理和统一构建方面有优势，现在缺失的是一些工具链辅助打包
