### ISSUE TITLE
MOD管理开发需求

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#1189]
1、遍历\wuxia_launch_Data\StreamingAssets下的所有子目录和压缩包（7z以及zip格式），每个子目录或压缩包作为一个MOD，读取到后读取其中的xml文件获取MOD名称以及介绍、作者、版本号，并显示其中特定名称的png格式图片作为封面。不包含特定名称的xml文件的目录和压缩包不作为MOD显示
2、游戏启动时，若当前MOD加载失败，则显示MOD管理界面以选择其他MOD。

**Comment by viruscamp** [comment]
除了主程序所在目录
SteamLibrary\steamapps\common\群侠传，启动！\wuxia_launch_Data\StreamingAssets
最好还要扫描workshop安装的目录
SteamLibrary\steamapps\workshop\content\2098790

**Comment by 0kk470** [comment]
这个功能目前是已经有人在开发了吗

**Comment by qige2016** [comment]
> 这个功能目前是已经有人在开发了吗

@easterNday 这位大佬在开发

**Comment by easterNday** [comment]
> > 这个功能目前是已经有人在开发了吗
> 
> @easterNday 这位大佬在开发

？

**Comment by 0kk470** [comment]
好的好的，辛苦大佬了
