### ISSUE TITLE
光明顶之后出不去

### ISSUE THREAD

**Issue by aktkyuyo** [jynew/jynew#1197]
![20220926014727_1](https://user-images.githubusercontent.com/36838365/192157727-c9201ebe-6f10-40ff-94c1-fb314504c7e4.jpg)
离开选项没了。

**Comment by aktkyuyo** [comment]
![image](https://user-images.githubusercontent.com/36838365/192306803-ec8955e3-c2ba-4a28-af7e-f0af5d6fa577.png)
其实已经触发过剧情了。
出口还是没有。
昨晚下了整个下项目。今天我看了你最新fix。我把触发离开的接口放到ka88.lua。
![image](https://user-images.githubusercontent.com/36838365/192308303-7565a5e4-b196-4b91-90a1-9a5ab2510e34.png)
！！！！！！！！！！！已经可以出去了。！！！！！！！！！！！
我现在回想过程，希望有点帮助，有些地方不一定准确：
1 进来光明顶第一次，存档， 然后触发战斗失败了。
2 加载存档，没离开选项，能进战斗；
3 打完，直到他们5个人从中间，回到各自的位置，都没离开出口。（试过反复加载1的存档，重新打，还是一样）
4 在他们5个人，回去各自的位置之后，我存档了。所以就没触发你加的fix
ps：感谢

**Comment by citydream163** [comment]
主要原因是lua代码没有全部运行完成，然后你中途做了保存动作，致使后续代码没有执行下去造成的，看来plus版要把小地图保存功能关闭才能从根本上解决问题。
