### ISSUE TITLE
【重要】触发器机制待调整

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#12]
游戏内物体交互由进入区域触发改为角色面朝向触发（避免同时处于多个触发器激活状态）

**Comment by chenggongchina** [comment]
![00~W0~}HA{X@H{A(W2N_FHG](https://user-images.githubusercontent.com/7448857/119214216-ae5dbf80-baf7-11eb-888d-61865769cfd6.png)
示意图

**Comment by chenggongchina** [comment]
额，没人认领下这个任务么

**Comment by peijiZhu** [comment]
我来处理一下

**Comment by chenggongchina** [comment]
> 我来处理一下

并没有提交pull request，我已经修了。

**Comment by chenggongchina** [comment]
目前是只会唯一判断身前120度1米以内可交互物体，选取第一个可被交互
鼠标点击交互已禁用

**Comment by PatrickStar00** [comment]
> > 我来处理一下
> 
> 并没有提交拉取请求，我已经修改了。

emm 尴尬了
