### ISSUE TITLE
关于修改器

### ISSUE THREAD

**Issue by DeerLim** [jynew/jynew#1211]
能发布一款修改器么？ 或者技能编辑器 或者类似经典金庸修改器的存档修改功能？

**Comment by MephistoSatanDevil** [comment]
记事本就能修改存档

**Comment by qige2016** [comment]
技能编辑器现在分Excel记录数据和特效编辑器。
存档现在是明文记录。

**Comment by DeerLim** [comment]
> 记事本就能修改存档

谢谢 已经发现了

**Comment by DeerLim** [comment]
> 技能编辑器现在分Excel记录数据和特效编辑器。 存档现在是明文记录。

感谢答复，话说技能编辑部份我想要修改一些技能的伤害 范围，现在有办法在游戏客户端里修改么？

**Comment by qige2016** [comment]
现在只能在unity里面修改

**Comment by DeerLim** [comment]
> 现在只能在unity里面修改

原来只能用unity啊...  感谢回复
