### ISSUE TITLE
Steam 20220929 事件触发的属性增加计算有误

### ISSUE THREAD

**Issue by viruscamp** [jynew/jynew#1223]
渡城主角，进无名窟，升了两三次蓝翔步，穿着胜马靴，算装备轻功是 83，拿无名指时轻功属性只增加了 17
读档，不穿胜马靴，再拿无名指时轻功属性增加 30

**Comment by qige2016** [comment]
这块确实有问题，没判断当前是否超过max

**Comment by qige2016** [comment]
我看了下源码，角色本身的属性点最多加到100

**Comment by viruscamp** [comment]
加属性时，要先把装备的扣掉。
