### ISSUE TITLE
点击交互后会卡住，有音乐声音，菜单也打得开然后人物移动不了用鼠标和手柄都试过了也没用，使用的是残魂mod

### ISSUE THREAD

**Issue by HAHATian** [jynew/jynew#1243]
<img width="1280" alt="群侠传，启动！ Screenshot 2022 10 08 - 12 15 16 32" src="https://user-images.githubusercontent.com/70826763/194687778-ea9baa8c-2047-4bb1-a00b-67bc4b499881.png">

**Comment by qige2016** [comment]
这边看到是xlua协程报错，详细的还得点击最后一条报错查看

**Comment by HAHATian** [comment]
<img width="1280" alt="群侠传，启动！ Screenshot 2022 10 08 - 13 06 31 77" src="https://user-images.githubusercontent.com/70826763/194689646-cfe97cc2-1031-4618-8171-64e57e7ec162.png">

**Comment by HAHATian** [comment]
这个是吗？

**Comment by qige2016** [comment]
> 这个是吗？

是的，感谢提issue，我们后续解决

**Comment by qige2016** [comment]
请问下是不是使用了手柄

**Comment by HAHATian** [comment]
是的

**Comment by HAHATian** [comment]
但是没用手柄之前也出现过这种状况

**Comment by qige2016** [comment]
> 但是没用手柄之前也出现过这种状况

好的，目前报错显示是这个问题，后面解决

**Comment by HAHATian** [comment]
好的，辛苦
