### ISSUE TITLE
在神雕山洞里无法打蛇 如果直接绕过去找杨过之后百花谷不出蜂巢

### ISSUE THREAD

**Issue by Mr79Mr79** [jynew/jynew#1245]
找杨过，把断肠草给他，之后带他去周伯通那，把玉蜂浆给周伯通之后，没有出现蜂巢。后面就无法进行了。

**Comment by qige2016** [comment]
麻烦附带下reporter里面的错误日志

**Comment by MephistoSatanDevil** [comment]
> 找杨过，把断肠草给他，之后带他去周伯通那，把玉蜂浆给周伯通之后，没有出现蜂巢。后面就无法进行了。

哪个模组？
