### ISSUE TITLE
开局身上无银两情况下对河洛客栈小二使用物品再取消后无法再触发交互

### ISSUE THREAD

**Issue by imcloud** [jynew/jynew#126]
游玩时最新commit：9e7adc2

复现步骤：
1.开局直奔河洛客栈
2.与店小二对话，使用物品，发现没银两，取消使用
3.再次对话无反应
4.出大地图部分场景光柱不再提示进入按钮

另外，猜测其他该使用物品却取消使用的情况可能也一样有这个问题，没做证实

**Comment by imcloud** [comment]
我不知道build号在哪里看，只能以当时的提交作为问题出现的游戏版本

**Comment by eaphone** [comment]
e3f750f fix this issue.
