### ISSUE TITLE
Steam云存档超大，包括所有 WinAppDataLocalLow 下的文件

### ISSUE THREAD

**Issue by viruscamp** [jynew/jynew#1260]
我的云存档有200多MB, 看了一下，有下面这些东西:
你们是不是设置错误，把 WinAppDataLocalLow 全部包括了?
Steam\userdata\${userid}\2098790\remotecache.vdf 包含所有上传文件信息，其中部分内容
```json
"2098790"
{
	"ChangeNumber"		"0"
	"ostype"		"16"
	"Intel/ShaderCache/01a6f56db57982a284ff4fb532869bf6369564779c0b39442e84d9e763b0e0ed"
	{
		"root"		"12"
		"size"		"26"
		"localtime"		"1607057778"
		"time"		"1607057778"
		"remotetime"		"1607057778"
		"sha"		"21d986c5039547bc03fd3f6699ffe9772adb4c32"
		"syncstate"		"1"
		"persiststate"		"0"
		"platformstosync2"		"-1"
	}
	"Oracle/Java/jdk1.8.0_181_x64/au.msi"
	{
		"root"		"12"
		"size"		"0"
		"localtime"		"0"
		"time"		"0"
		"remotetime"		"0"
		"sha"		"0000000000000000000000000000000000000000"
		"syncstate"		"1"
		"persiststate"		"1"
		"platformstosync2"		"-1"
	}

```

**Comment by viruscamp** [comment]
我看了下文档 https://partner.steamgames.com/doc/features/cloud
应该是
Root: WinAppDataLocalLow
Subdirectory: jynew/wuxia_launch
是不是没设 Subdirectory ?

**Comment by viruscamp** [comment]
问题非常严重，必须尽量解决。

占用空间超大
同步失败
覆盖其他程序的数据
数据泄漏

**Comment by qige2016** [comment]
欧了
![image](https://user-images.githubusercontent.com/18051955/196041494-5a927a2f-dc42-404b-8a2c-7458e0aae542.png)

**Comment by viruscamp** [comment]
基本可以了，最好再排除下面的这些类似文件

jynew/wuxia_launch/Player-prev.log
jynew/wuxia_launch/Player.log
jynew/wuxia_launch/Unity/local.5f36eb911cb7e844984b9173b02f19d0/Analytics/ArchivedEvents/166593268900002.9b334c5c/s
