### ISSUE TITLE
战斗时AI使用不减数量，或数量为0时依然会使用道具

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#1266]
导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。
物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。

**Comment by FengQi777** [comment]
可以把这个issue交给我解决么，我想尝试一下

**Comment by 0kk470** [comment]
> 导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。 物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。

关键代码在[该处](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/BattleManager/AIManager.cs#L723)
加油

**Comment by FengQi777** [comment]
> > 导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。 物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。
> 
> 关键代码在[该处](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/BattleManager/AIManager.cs#L723) 加油

好的，我会努力

**Comment by 0kk470** [comment]
> > > 导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。 物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。
> > 
> > 
> > 关键代码在[该处](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/BattleManager/AIManager.cs#L723) 加油
> 
> 好的，我会努力

另外，现在的AI角色的道具背包数据是跟着存档走的。
因此道具的数据对AI 来说就是个模板，单场战斗的数量变化不会影响存档本身AI角色的道具数量。
你可能得考虑下在单场战斗中用一个临时数据来存储敌方AI的道具使用情况进行相关计算。

**Comment by 0kk470** [comment]
> > > > 导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。 物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。
> > > 
> > > 
> > > 关键代码在[该处](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/BattleManager/AIManager.cs#L723) 加油
> > 
> > 
> > 好的，我会努力
> 
> 另外，现在的AI角色的道具背包数据是跟着存档走的。 因此道具的数据对敌方AI 来说就是个模板，单场战斗的数量变化不会影响存档本身AI角色的道具数量。 你可能得考虑下在单场战斗中用一个临时数据来存储敌方AI的道具使用情况进行相关计算。

上面当我没说，现在进战斗后是重置过的

**Comment by FengQi777** [comment]
> > 导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。 物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。
> 
> 关键代码在[该处](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/BattleManager/AIManager.cs#L723) 加油

[这里](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L464)按理来说已经对敌人的item进行了Remove操作

**Comment by 0kk470** [comment]
> > > 导致敌人可无限吃药。本来能够靠把敌人药品消耗光打胜的战斗可能会变得无法打赢。 物品数量为0的时候应该直接从角色拥有物品列表里直接移除条目，而不是保留一个数量为0的道具。
> > 
> > 
> > 关键代码在[该处](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/BattleManager/AIManager.cs#L723) 加油
> 
> [这里](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L464)按理来说已经对敌人的item进行了Remove操作

是的，这里我也发现了，之前测了十几场不同的战斗没复现类似的问题，我觉得这个问题会不会是某个角色的回血道具数量配置的太多了，导致玩家认为AI可以无限用药。

**Comment by qige2016** [comment]
这个问题先关闭了
