### ISSUE TITLE
Steam 20221018 严重问题

### ISSUE THREAD

**Issue by viruscamp** [jynew/jynew#1268]
现有的3个mod都出现了这个问题

新建存档测试
1. 遇敌自动胜利 包括家的陌生人 林平之
2. 升级后 御剑 医疗等被清0，只有 攻 防 轻功 特殊
3. 同伴 段誉 生命-8944 内力 -8967

存档里面除了主角其他人 MaxMp MaxHp 都是负的，大概就是1和3的原因

**Comment by viruscamp** [comment]
刚更了新版本
1, 3 应该是解决了

下面的没解决
升级后 御剑 医疗等被清0，只有 攻 防 轻功 特殊

**Comment by fcxp2020** [comment]
plus 这边貌似还是这个毛病
