### ISSUE TITLE
黯然销魂掌掌谱

### ISSUE THREAD

**Issue by fcxp2020** [jynew/jynew#1269]
在古墓再次遇到杨过应该会给黯然销魂掌掌谱，但现在没有

**Comment by MephistoSatanDevil** [comment]
哪个MOD?

**Comment by qq634488405** [comment]
3D重制有这个问题，PLUS不清楚有没有

> 哪个MOD?

**Comment by MephistoSatanDevil** [comment]
> 3D重制有这个问题，PLUS不清楚有没有
> 
> > 哪个MOD?

提供一下游戏存档目录中的“Player.log”和“Player-prev.log”
最好能把存档文件也附带发一下。

**Comment by qq634488405** [comment]
> > 3D重制有这个问题，PLUS不清楚有没有
> > > 哪个MOD?
> 
> 提供一下游戏存档目录中的“Player.log”和“Player-prev.log” 最好能把存档文件也附带发一下。

发到邮箱jy_remastered@163.com了
`
Talk(0, "杨兄，长年待在这古墓中，你受的了吗？", "talkname0", 1);
Talk(58, "习惯就好了，龙儿还从小就住在这呢，这是我们古墓派的传统。", "talkname58", 0);
Talk(0, "兄弟近来如何？", "talkname0", 1);
ModifyEvent(-2, -2, -2, -2, 439, -1, -1, -2, -2, -2, -2, -2, -2);
if AskJoin () == true then goto label0 end;
    Talk(0, "一切顺利，你夫妇俩可还好吧。", "talkname0", 1);
    Talk(58, "托你的福，一切还好。", "talkname58", 0);
    do return end;
::label0::
    Talk(0, "近日旅途有些不顺，此次前来是想请杨兄加入，助我一臂之力。", "talkname0", 1);
    Talk(58, "那有什么问题，别的没有，就是有“一臂”。", "talkname58", 0);
    Talk(0, "杨兄说笑了。", "talkname0", 1);
    Talk(58, "此次重出江湖，正好试试新练成的“黯然销魂掌”。", "talkname58", 0);
    Talk(0, "那就走吧。", "talkname0", 1);
    if TeamIsFull() == false then goto label1 end;
        Talk(58, "你的队伍已满，我无法加入。", "talkname58", 0);
        do return end;
::label1::
        DarkScence();
        jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过加入队伍       
        ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2);      
        LightScence();
        Join(58);

do return end;
执行lua: ka438
lua执行完毕: ka438`

应该是这段吧，没有additem

**Comment by chenggongchina** [comment]
应该是再入队角色身上携带道具的逻辑错误，需要检查下

**Comment by fcxp2020** [comment]
plus也有这个问题

**Comment by MephistoSatanDevil** [comment]
> > > 3D重制有这个问题，PLUS不清楚有没有
> > > > 哪个MOD?
> > 
> > 
> > 提供一下游戏存档目录中的“Player.log”和“Player-prev.log” 最好能把存档文件也附带发一下。
> 
> 发到邮箱[jy_remastered@163.com](mailto:jy_remastered@163.com)了 ` Talk(0, "杨兄，长年待在这古墓中，你受的了吗？", "talkname0", 1); Talk(58, "习惯就好了，龙儿还从小就住在这呢，这是我们古墓派的传统。", "talkname58", 0); Talk(0, "兄弟近来如何？", "talkname0", 1); ModifyEvent(-2, -2, -2, -2, 439, -1, -1, -2, -2, -2, -2, -2, -2); if AskJoin () == true then goto label0 end; Talk(0, "一切顺利，你夫妇俩可还好吧。", "talkname0", 1); Talk(58, "托你的福，一切还好。", "talkname58", 0); do return end; ::label0:: Talk(0, "近日旅途有些不顺，此次前来是想请杨兄加入，助我一臂之力。", "talkname0", 1); Talk(58, "那有什么问题，别的没有，就是有“一臂”。", "talkname58", 0); Talk(0, "杨兄说笑了。", "talkname0", 1); Talk(58, "此次重出江湖，正好试试新练成的“黯然销魂掌”。", "talkname58", 0); Talk(0, "那就走吧。", "talkname0", 1); if TeamIsFull() == false then goto label1 end; Talk(58, "你的队伍已满，我无法加入。", "talkname58", 0); do return end; ::label1:: DarkScence(); jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过加入队伍 ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2); LightScence(); Join(58);
> 
> do return end; 执行lua: ka438 lua执行完毕: ka438`
> 
> 应该是这段吧，没有additem

不是这段。应该是在见到小龙女的事件时，有一本黯然销魂掌加入到杨过身上，而不是杨过入队时，加入到玩家身上。

**Comment by qq634488405** [comment]
> > > > 3D重制有这个问题，PLUS不清楚有没有
> > > > > 哪个MOD?
> > > 
> > > 
> > > 提供一下游戏存档目录中的“Player.log”和“Player-prev.log” 最好能把存档文件也附带发一下。
> > 
> > 
> > 发到邮箱[jy_remastered@163.com](mailto:jy_remastered@163.com)了 ` Talk(0, "杨兄，长年待在这古墓中，你受的了吗？", "talkname0", 1); Talk(58, "习惯就好了，龙儿还从小就住在这呢，这是我们古墓派的传统。", "talkname58", 0); Talk(0, "兄弟近来如何？", "talkname0", 1); ModifyEvent(-2, -2, -2, -2, 439, -1, -1, -2, -2, -2, -2, -2, -2); if AskJoin () == true then goto label0 end; Talk(0, "一切顺利，你夫妇俩可还好吧。", "talkname0", 1); Talk(58, "托你的福，一切还好。", "talkname58", 0); do return end; ::label0:: Talk(0, "近日旅途有些不顺，此次前来是想请杨兄加入，助我一臂之力。", "talkname0", 1); Talk(58, "那有什么问题，别的没有，就是有“一臂”。", "talkname58", 0); Talk(0, "杨兄说笑了。", "talkname0", 1); Talk(58, "此次重出江湖，正好试试新练成的“黯然销魂掌”。", "talkname58", 0); Talk(0, "那就走吧。", "talkname0", 1); if TeamIsFull() == false then goto label1 end; Talk(58, "你的队伍已满，我无法加入。", "talkname58", 0); do return end; ::label1:: DarkScence(); jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过加入队伍 ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2); LightScence(); Join(58);
> > do return end; 执行lua: ka438 lua执行完毕: ka438`
> > 应该是这段吧，没有additem
> 
> 不是这段。应该是在见到小龙女的事件时，有一本黯然销魂掌加入到杨过身上，而不是杨过入队时，加入到玩家身上。

从这个ka438往前翻，在ka436脚本上杨过离队加了一本黯然销魂掌
    Talk(0, "不知杨兄现在有何打算。", "talkname0", 1);
    Talk(58, "我想先和龙儿回古墓中，兄弟将来若有什么困难，尽管到古墓中找我夫妇俩。", "talkname58", 1);
    Talk(0, "杨兄慢走，愿你夫妇俩别再分离。", "talkname0", 1);
    Talk(58, "那我夫妇俩先走了，祝兄弟一路顺风。", "talkname58", 1);
    DarkScence();
    SetScenceMap(18, 1, 44, 31, 0);
    SetScenceMap(18, 1, 44, 30, 0);
    jyx2_FixMapObject("古墓开门",1);
    ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -6068, -1, -1, -2, -2, -2);--小龙女贴图设置（用负代表消失）
    jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过离开
    jyx2_ReplaceSceneObject("", "NPC/小龙女", "");--小龙女离开
    ModifyEvent(18, 1, 1, 1, 438, -1, -1, 6188, 6188, 6188, -2, -2, -2);
    ModifyEvent(18, 0, 1, 1, 440, -1, -1, 6068, 6068, 6068, -2, -2, -2);
    jyx2_ReplaceSceneObject("18", "NPC/杨过", "1");--杨过出现
    jyx2_ReplaceSceneObject("18", "NPC/小龙女", "1");--小龙女出现
    ModifyEvent(18, 2, -2, -2, 442, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(18, 3, -2, -2, 442, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(18, 4, -2, -2, 443, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(18, 5, -2, -2, 443, -1, -1, -2, -2, -2, -2, -2, -2);
    LearnMagic2(58, 24, 1);--杨过习得1级黯然销魂掌
    NPCAddItem(58, 61, 1);--杨过获得黯然销魂掌秘籍
    Leave(58);--杨过离队
    LightScence();
    Talk(0, "“问世间情是何物，直叫人生死相许”。他们夫妇俩真是令人羡慕的神仙侠侣。“神仙侠侣”！……“神雕侠侣”？对了，还有那头老雕，那本书该不会是在他俩身上吧。看来有空还要再前往古墓找他夫妇俩。", "talkname0", 1);
    do return end;
::label0::

杨过入队的时候身上是有秘籍的

**Comment by qq634488405** [comment]
> > > > 3D重制有这个问题，PLUS不清楚有没有
> > > > > 哪个MOD?
> > > 
> > > 
> > > 提供一下游戏存档目录中的“Player.log”和“Player-prev.log” 最好能把存档文件也附带发一下。
> > 
> > 
> > 发到邮箱[jy_remastered@163.com](mailto:jy_remastered@163.com)了 ` Talk(0, "杨兄，长年待在这古墓中，你受的了吗？", "talkname0", 1); Talk(58, "习惯就好了，龙儿还从小就住在这呢，这是我们古墓派的传统。", "talkname58", 0); Talk(0, "兄弟近来如何？", "talkname0", 1); ModifyEvent(-2, -2, -2, -2, 439, -1, -1, -2, -2, -2, -2, -2, -2); if AskJoin () == true then goto label0 end; Talk(0, "一切顺利，你夫妇俩可还好吧。", "talkname0", 1); Talk(58, "托你的福，一切还好。", "talkname58", 0); do return end; ::label0:: Talk(0, "近日旅途有些不顺，此次前来是想请杨兄加入，助我一臂之力。", "talkname0", 1); Talk(58, "那有什么问题，别的没有，就是有“一臂”。", "talkname58", 0); Talk(0, "杨兄说笑了。", "talkname0", 1); Talk(58, "此次重出江湖，正好试试新练成的“黯然销魂掌”。", "talkname58", 0); Talk(0, "那就走吧。", "talkname0", 1); if TeamIsFull() == false then goto label1 end; Talk(58, "你的队伍已满，我无法加入。", "talkname58", 0); do return end; ::label1:: DarkScence(); jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过加入队伍 ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2); LightScence(); Join(58);
> > do return end; 执行lua: ka438 lua执行完毕: ka438`
> > 应该是这段吧，没有additem
> 
> 不是这段。应该是在见到小龙女的事件时，有一本黯然销魂掌加入到杨过身上，而不是杨过入队时，加入到玩家身上。

从这个ka438往前翻，在ka436脚本上杨过离队加了一本黯然销魂掌
    Talk(0, "不知杨兄现在有何打算。", "talkname0", 1);
    Talk(58, "我想先和龙儿回古墓中，兄弟将来若有什么困难，尽管到古墓中找我夫妇俩。", "talkname58", 1);
    Talk(0, "杨兄慢走，愿你夫妇俩别再分离。", "talkname0", 1);
    Talk(58, "那我夫妇俩先走了，祝兄弟一路顺风。", "talkname58", 1);
    DarkScence();
    SetScenceMap(18, 1, 44, 31, 0);
    SetScenceMap(18, 1, 44, 30, 0);
    jyx2_FixMapObject("古墓开门",1);
    ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -6068, -1, -1, -2, -2, -2);--小龙女贴图设置（用负代表消失）
    jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过离开
    jyx2_ReplaceSceneObject("", "NPC/小龙女", "");--小龙女离开
    ModifyEvent(18, 1, 1, 1, 438, -1, -1, 6188, 6188, 6188, -2, -2, -2);
    ModifyEvent(18, 0, 1, 1, 440, -1, -1, 6068, 6068, 6068, -2, -2, -2);
    jyx2_ReplaceSceneObject("18", "NPC/杨过", "1");--杨过出现
    jyx2_ReplaceSceneObject("18", "NPC/小龙女", "1");--小龙女出现
    ModifyEvent(18, 2, -2, -2, 442, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(18, 3, -2, -2, 442, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(18, 4, -2, -2, 443, -1, -1, -2, -2, -2, -2, -2, -2);
    ModifyEvent(18, 5, -2, -2, 443, -1, -1, -2, -2, -2, -2, -2, -2);
    LearnMagic2(58, 24, 1);--杨过习得1级黯然销魂掌
    NPCAddItem(58, 61, 1);--杨过获得黯然销魂掌秘籍
    Leave(58);--杨过离队
    LightScence();
    Talk(0, "“问世间情是何物，直叫人生死相许”。他们夫妇俩真是令人羡慕的神仙侠侣。“神仙侠侣”！……“神雕侠侣”？对了，还有那头老雕，那本书该不会是在他俩身上吧。看来有空还要再前往古墓找他夫妇俩。", "talkname0", 1);
    do return end;
::label0::

杨过入队的时候身上是有秘籍的

**Comment by fcxp2020** [comment]
> > > > > 3D制有这个问题，加之有重有没有
> > > > > > 哪个MOD？
> > > > 
> > > > 
> > > > 提供一下游戏文件中的“Player.log”和“Playerprev.log”最好能把文件也记录一下。
> > > 
> > > 
> > > 发到邮箱[jy_remastered@163.com](mailto:jy_remastered@163.com)了` Talk(0, "杨兄，长年待在这古墓中，你受的了吗？", "talkname0", 1); Talk(58, "习惯就好了，龙儿还从小就住在这呢，这是我们古墓派的传统。", "talkname58", 0); Talk(0, "兄弟近来如何？", "talkname0", 1); ModifyEvent(-2, -2, -2, -2, 439, -1, -1, -2, -2, -2, -2, -2, -2); if AskJoin () == true then goto label0 end; Talk(0, "一切顺利，你夫妇俩可还好吧。", "talkname0", 1); Talk(58, "托你的福，一切还好。", "talkname58", 0); do return end; ::label0:: Talk(0, "近日旅途有些不顺，此次前来是想请杨兄加入，助我一臂之力。", "talkname0", 1); Talk(58, "那有什么问题，别的没有，就是有“一臂”。", "talkname58", 0); Talk(0, "杨兄说笑了。", "talkname0", 1); Talk(58, "此次重出江湖，正好试试新练成的“黯然销魂掌”。", "talkname58", 0); Talk(0, "那就走吧。", "talkname0", 1); if TeamIsFull() == false then goto label1 end; Talk(58, "你的队伍已满，我无法加入。", "talkname58", 0); do return end; ::label1:: DarkScence(); jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过加入队伍 ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -1, -1, -1, -2, -2, -2); LightScence(); Join(58); do return end; 执行lua: ka438 lua执行完毕: ka438`
> > > 应该是吧，没有addite
> > 
> > 
> > 应该是在小龙女的事件发生的时候，黯然杀魂掌加入到杨过的那个时候，而不是杨过入队，加入到他们之中。
> 
> 这个ka438往前不知翻，在上杨过剧本加了了黯然销往魂掌 Talk(0, "杨兄现在走43队。", "talkname", 1); Talk(58,《我想先和龙儿回古墓中，兄弟俩如果有什么困难，尽管到古墓中找我俩。》,《talkname58》,1); Talk(0, "杨兄慢走，愿你俩再分开。", "talkname0", 1); Talk(58, "那我夫妇俩先走了，祝兄弟一路顺风。", "talkname58", 1); 黑暗场景（）； SetScenceMap(18, 1, 44, 31, 0); SetScenceMap(18, 1, 44, 30, 0); jyx2_FixMapObject("古墓开启",1); ModifyEvent(-2, -2, 0, 0, -1, -1, -1, -6068, -1, -1, -2, -2, -2);--小龙女贴图设置（用负代表）消失 jyx2_ReplaceSceneObject("", "NPC/杨过", "");--杨过离开 jyx2_ReplaceSceneObject("", "NPC/小龙女", "");--小龙女离开 ModifyEvent(18, 1, 1, 1, 438, -1, -1, 6188, 6188、6188、-2、-2、-2）； ModifyEvent(18, 0, 1, 1, 440, -1, -1, 6068, 6068, 6068, -2, -2, -2); jyx2_ReplaceSceneObject("18", "NPC/杨过", "1");--杨过出现 jyx2_ReplaceSceneObject("18", "NPC/小龙女", "1");--小龙女出现 ModifyEvent(18, 2, -2、-2、442、-1、-1、-2、-2、-2、-2、-2、-2）； ModifyEvent(18, 3, -2, -2, 442, -1, -1, -2, -2, -2, -2, -2, -2); ModifyEvent(18, 4, -2, -2, 443, -1, -1, -2, -2, -2, -2, -2, -2); ModifyEvent(18, 5, -2, -2, 443, -1, -1, -2, -2, -2, -2, -2, -2); LearnMagic2(58, 24, 1);--杨过得1级黯然销魂掌 NPCAddItem(58, 61, 1);--杨过获得黯然销魂掌秘籍 Leave(58);--杨过离 LightScence(); Talk(0,“问世间情是何物，直叫人生死相许”。他们夫妻俩真是“令人羡慕的神仙侠侣”。“神仙侠伴侣”！……“神雕侠侣”？对了还有那头老雕，那本书该不会是在他俩吧。看来有空域再去古墓寻找他夫妇。", "talkname0", 1); 做返回结束； ::标签0::
> 
> 杨过入队的时候是有秘籍的

但是杨过再加入秘籍就不见了
