### ISSUE TITLE
开局直接点击左侧的传送列表，传送到金轮寺，然后控制人物移动并与和尚对话，会报下面的错误，且无法进行下一步的任务

### ISSUE THREAD

**Issue by XINCGer** [jynew/jynew#127]
RT
![a1](https://user-images.githubusercontent.com/10908565/120959285-f9c8cc80-c78b-11eb-9a58-34d77f5d26b6.png)
![a2](https://user-images.githubusercontent.com/10908565/120959287-faf9f980-c78b-11eb-97aa-d1ee7c78cb14.png)
![a3](https://user-images.githubusercontent.com/10908565/120959291-fcc3bd00-c78b-11eb-8e23-a23e7961bc95.png)

**Comment by eaphone** [comment]
#197 优化场景后已无法复现
