### ISSUE TITLE
河洛客栈和店小二对话，多几次必然卡死后无法移动，esc可退回到大地图。

### ISSUE THREAD

**Issue by DemoYolk** [jynew/jynew#128]
**第一种错误**
错误：在一个lua未结束的时候，启动另一个lua线程, path=jygame/ka666
UnityEngine.Debug:LogError (object)
Jyx2.LuaExecutor:Execute (string,System.Action,Jyx2.JYX2LuaEvnContext) (at Assets/Scripts/LuaCore/LuaExecutor.cs:28)
GameEventManager:ExecuteLuaEvent (int,Jyx2.JYX2LuaEvnContext) (at Assets/Scripts/GameEventManager.cs:239)
GameEventManager:<ShowInteractUIPanel>b__8_0 () (at Assets/Scripts/GameEventManager.cs:139)
InteractUIPanel:OnBtnClick (int) (at Assets/Scripts/Jyx2UIScripts/InteractUIPanel.cs:41)
InteractUIPanel:<OnCreate>b__4_0 () (at Assets/Scripts/Jyx2UIScripts/InteractUIPanel.cs:14)
Jyx2_UIBase/<>c__DisplayClass12_0:<BindListener>b__0 () (at Assets/Scripts/Jyx2UIScripts/Jyx2_UIBase.cs:70)
UnityEngine.EventSystems.EventSystem:Update () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:385)
**第二种错误**
内部错误：当前的eventId为空，但是指定修改当前event
UnityEngine.Debug:LogError (object)
Jyx2.Jyx2LuaBridge/<>c__DisplayClass7_0:<ModifyEvent>b__0 () (at Assets/Scripts/LuaCore/Jyx2LuaBridge.cs:113)
Jyx2.Jyx2LuaBridge/<>c__DisplayClass82_0:<RunInMainThrad>b__0 (object) (at Assets/Scripts/LuaCore/Jyx2LuaBridge.cs:1000)
Loom:Update () (at Assets/Scripts/LuaCore/Loom.cs:148)

**Comment by chenggongchina** [comment]
已修复
