### ISSUE TITLE
打包导出之后无法进入游戏

### ISSUE THREAD

**Issue by ks0ng** [jynew/jynew#1280]
当前 commit 2800021d08a5444887b7791187265d214f686028

在Unity里可以编译并进入游戏，但是打包导出之后无法进入游戏，出现如下报错
![jynew_launch_issue](https://user-images.githubusercontent.com/34049080/197858950-d528f31b-9c0e-47dc-8a25-3ad4cedeac47.jpg)

**Comment by 0kk470** [comment]
需要将mod相关的ab资源放置到以下目录

**Comment by 0kk470** [comment]
之后考虑把 一键打包这的流程再优化下，最好是把BuildPlayer和Mod导出一起自动执行了。
