### ISSUE TITLE
找不到开发文档中提到的jyx2\excel文件

### ISSUE THREAD

**Issue by oywq2020** [jynew/jynew#1283]
找不到开发文档中提到的jyx2\excel文件
https://github.com/jynew/jynew/wiki/3.3%E9%85%8D%E7%BD%AE%E8%A1%A8%E5%8A%A0%E8%BD%BD%E5%92%8C%E8%AF%BB%E5%8F%96

**Comment by 0kk470** [comment]
Excel配置现在路径```Asset/Mods/Mod名/Configs```下
生成配置使用```Asset/Mods/Mod名```下的ModSetting文件里的```生成配置表```按钮
