### ISSUE TITLE
一些想法

### ISSUE THREAD

**Issue by fcxp2020** [jynew/jynew#1290]
1.怎么样让主角可以学习特殊武功
2.《葵花宝典》说是任何人可以学，为什么还是有修炼条件
3.可不可以让一种武学修炼后可以加生命值，及生命值的武学太少而且加的也少，只有九阳神功，九阴真经，葵花宝典

**Comment by chenggongchina** [comment]
都可以做，但金庸3D的初衷是完全还原原版。所以并不会去进行修改，你可以在MOD中或者建议其他MOD作者去开发。

**Comment by MephistoSatanDevil** [comment]
> 1.怎么样让主角可以学习特殊武功 2.《葵花宝典》说是任何人可以学，为什么还是有修炼条件 3.可不可以让一种武学修炼后可以加生命值，及生命值的武学太少而且加的也少，只有九阳神功，九阴真经，葵花宝典

这个项目内置的MOD是《群侠传，启动！》中附带的《渡城残魂传》。
