### ISSUE TITLE
大地图丐帮与古墓建筑优化

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#13]
![image](https://user-images.githubusercontent.com/22126740/119214613-c7b43b00-bafa-11eb-939c-642e288c90f3.png)

**Comment by eaphone** [comment]
侠客岛也缺少建筑（是否需要?）

**Comment by eaphone** [comment]
古墓派建筑需要重构
![image](https://user-images.githubusercontent.com/22126740/119216004-ac99f900-bb03-11eb-96dd-df85aa37f491.png)

**Comment by chenggongchina** [comment]
@HYYellowOne 考虑解决一下？

**Comment by HYYellowOne** [comment]
大地图上缺少建筑的地点一般是该地点本身没有建筑
![image](https://user-images.githubusercontent.com/51065949/119221533-7029c580-bb22-11eb-92c5-a558fccbb1d8.png)
我可以尝试让这些地点特征明显些

**Comment by eaphone** [comment]
> 大地图上缺少建筑的地点一般是该地点本身没有建筑
> ![image](https://user-images.githubusercontent.com/51065949/119221533-7029c580-bb22-11eb-92c5-a558fccbb1d8.png)
> 我可以尝试让这些地点特征明显些

是不是可以参考原版。加些草席，帐篷

**Comment by chenggongchina** [comment]
调整古墓派大地图样子
![image](https://user-images.githubusercontent.com/7448857/132542007-14fcc6db-f4d1-4887-b19d-774b8c633c2d.png)

**Comment by chenggongchina** [comment]
![image](https://user-images.githubusercontent.com/7448857/132542990-32405be2-07a4-48d7-9fd8-db69c1457023.png)
侠客岛
