### ISSUE TITLE
Can not get a playable version 

### ISSUE THREAD

**Issue by runforu** [jynew/jynew#1312]
我用了一整天都没能下载一个Windows版本。steam china 没有这个游戏，国外的steam注册不了账户。
release里面竟然放了一个百度盘的链接。百度盘是个啥玩意大家都知道，总之是不安装百度全家桶下载不了。

建议你们能把release版的bin直接放到GitHub里面。

**Comment by MephistoSatanDevil** [comment]
项目主页包体下载页面的第一个链接就是Steam地址，你确定你找不到？另外据我所知，目前还没有所谓的SteamChina专版上线。
