### ISSUE TITLE
游戏存档内应像原版的存档那样保存了道具信息和武功信息

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#1314]
原版存档中，不仅保存了所有NPC人物信息，同时保存了武功和物品相关信息。
通过存档编辑器就可以直接修改“当前存档中武功范围威力”或者“道具属性效果”等相关内容，而不会影响游戏其他存档。

使用场景：比如在制作MOD的时候，如果有触发某事件后，葵花宝典秘籍改为可修炼出葵花神功（JY.Thing[93]["练出武功"]=26;），或者修改武功威力（JY.Wugong[31]["攻击力" .. 10]=80;），修改完毕后，是保存在存档里的。

现在的游戏存档里似乎不像原版的存档那样保存了道具信息和武功信息，这样的事件应该没法写。
原本的Excel中所存储的数据应当是游戏新建存档时的初始默认数据，而游戏运行时数据表应该存储在存档中，与基础数据无关。
随着游戏不断进行，角色属性或者道具属性发生变化的运行时数据存在存档里应当是合理的。

**Comment by chenggongchina** [comment]
不应保存在存档中，如果要修改应该修改对应的ID。
