### ISSUE TITLE
武功秘籍修炼条件限制有误

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#1316]
原版中，当角色已经学会某武功时，选择该武功秘籍修炼，会忽略修炼条件限制直接修炼，不会受条件限制。目前的版本似乎依然在判断修炼条件。

**Comment by FengQi777** [comment]
可以交给我试着去解决这个bug么

**Comment by qige2016** [comment]
> 可以交给我试着去解决这个bug么

你可以验证下，我感觉是没问题的

**Comment by MephistoSatanDevil** [comment]
> > 可以交给我试着去解决这个bug么
> 
> 你可以验证下，我感觉是没问题的

经测试，已经学会的武功，拳掌等属性未达标导致的无法修炼限制确实是忽略的。
但是，“仅XX可以修炼”条件未忽略。
比如六脉神剑，其他人如果改出来之后，再去装备秘籍会提示无法修炼。

**Comment by FengQi777** [comment]
> > 可以交给我试着去解决这个bug么
> 
> 你可以验证下，我感觉是没问题的

如果方便可否告知相关代码在哪个文件里

**Comment by qige2016** [comment]
> > > 可以交给我试着去解决这个bug么
> > 
> > 
> > 你可以验证下，我感觉是没问题的
> 
> 如果方便可否告知相关代码在哪个文件里

https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L494

**Comment by FengQi777** [comment]
> > > > 可以交给我试着去解决这个bug么
> > > 
> > > 
> > > 你可以验证下，我感觉是没问题的
> > 
> > 
> > 如果方便可否告知相关代码在哪个文件里
> 
> https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L494

感谢，已更改代码并提pr了

**Comment by qige2016** [comment]
> > > > > 可以交给我试着去解决这个bug么
> > > > 
> > > > 
> > > > 你可以验证下，我感觉是没问题的
> > > 
> > > 
> > > 如果方便可否告知相关代码在哪个文件里
> > 
> > 
> > https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L494
> 
> 感谢，已更改代码并提pr了

你这样改好像没啥区别啊，而且应该没问题的，先验证下问题是否存在

**Comment by FengQi777** [comment]
> > > > > > 可以交给我试着去解决这个bug么
> > > > > 
> > > > > 
> > > > > 你可以验证下，我感觉是没问题的
> > > > 
> > > > 
> > > > 如果方便可否告知相关代码在哪个文件里
> > > 
> > > 
> > > https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L494
> > 
> > 
> > 感谢，已更改代码并提pr了
> 
> 你这样改好像没啥区别啊，而且应该没问题的，先验证下问题是否存在

之前在装备武学时，如果有限制人物要求会先判断人物是否符合，不符合直接return false。现在会先判断是否已经学过，学过则不再判断人物要求是否符合，直接return true，没学过再判断人物是否符合

**Comment by qige2016** [comment]
> > > > > > > 可以交给我试着去解决这个bug么
> > > > > > 
> > > > > > 
> > > > > > 你可以验证下，我感觉是没问题的
> > > > > 
> > > > > 
> > > > > 如果方便可否告知相关代码在哪个文件里
> > > > 
> > > > 
> > > > https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L494
> > > 
> > > 
> > > 感谢，已更改代码并提pr了
> > 
> > 
> > 你这样改好像没啥区别啊，而且应该没问题的，先验证下问题是否存在
> 
> 之前在装备武学时，如果有限制人物要求会先判断人物是否符合，不符合直接return false。现在会先判断是否已经学过，学过则不再判断人物要求是否符合，直接return true，没学过再判断人物是否符合

好的，这样改大概是放宽了一种情况，

**Comment by qige2016** [comment]
@MephistoSatanDevil 看看这样改适合不

**Comment by d-earll** [comment]
> > > > > > > 可以交给我试着去解决这个bug么
> > > > > > 
> > > > > > 
> > > > > > 你可以验证下，我感觉是没问题的
> > > > > 
> > > > > 
> > > > > 如果方便可否告知相关代码在哪个文件里
> > > > 
> > > > 
> > > > https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L494
> > > 
> > > 
> > > 感谢，已更改代码并提pr了
> > 
> > 
> > 你这样改好像没啥区别啊，而且应该没问题的，先验证下问题是否存在
> 
> 之前在装备武学时，如果有限制人物要求会先判断人物是否符合，不符合直接return false。 现在会先判断是否已经学过，学过则不再判断人物要求是否符合，直接return true，没学过再判断人物是否符合

大哥能告诉我一下在哪里改吗？我也很困扰学习限定武功慢慢升级？但是不知道在哪里修改你说这个

**Comment by d-earll** [comment]
> 

大哥能告诉我一下在哪里改吗？ 我也很困扰学习限定武功慢慢升级？ 但是不知道在哪里修改你说这个？谢谢啦

**Comment by MephistoSatanDevil** [comment]
> @MephistoSatanDevil 看看这样改适合不

我这边测试未通过，给小虾米学会了六脉和降龙之后，连降龙都不能练了，更别说六脉了。

**Comment by FengQi777** [comment]
又去看了下相关代码，发现自己对foreach理解有误好像，foreach好像是不能直接return的
```
                    foreach (var wugong in Wugongs)
                    {
                        if (wugong.Key == item.Skill)
                            return true;
                    }
```
这里的return好像无法直接返回
[同时感觉原有些地方重复判断，比如对于满级武学来说，不需要在[这里](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L542)单独判断了，作为已学过武功直接安装就可以了。
同时               ` if ((int)item.ItemType == 2)`和` if (item.Skill != null)`好像都是在判断item是不是武学，然后我把这两个合并了
提交了一个新的pr，因为我还不太会进行测试，所以只能从代码层面分析，麻烦了

**Comment by FengQi777** [comment]
> > 
> 
> 你这个pr是不是改过什么不必要的东西？切换到你这个分支后，Game Tools菜单下的MOD导出功能就没有了。而且在编辑器中也无法正常游戏了？要不你再检查一下？试试看重新从主分支同步下去，然后只修改你要修改的那个文件，不要动其他的东西再看看？

好的我再检查一下，我这边测试了一下是在主角学会六脉神剑后已经可以正常装备剑法了，我重新从主分支同步一下

**Comment by FengQi777** [comment]
> 你这个pr是不是改过什么不必要的东西？切换到你这个分支后，Game Tools菜单下的MOD导出功能就没有了。而且在编辑器中也无法正常游戏了？要不你再检查一下？试试看重新从主分支同步下去，然后只修改你要修改的那个文件，不要动其他的东西再看看？

重新pr了一个，确认只更改了RoleInstance.cs中的一段代码

**Comment by 0kk470** [comment]
> 又去看了下相关代码，发现自己对foreach理解有误好像，foreach好像是不能直接return的
> 
> ```
>                     foreach (var wugong in Wugongs)
>                     {
>                         if (wugong.Key == item.Skill)
>                             return true;
>                     }
> ```
> 
> 这里的return好像无法直接返回 [同时感觉原有些地方重复判断，比如对于满级武学来说，不需要在[这里](https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L542)单独判断了，作为已学过武功直接安装就可以了。 同时 ` if ((int)item.ItemType == 2)`和` if (item.Skill != null)`好像都是在判断item是不是武学，然后我把这两个合并了 提交了一个新的pr，因为我还不太会进行测试，所以只能从代码层面分析，麻烦了

* `foreach`里直接return没问题
不过也可以写成这样
```CSharp
                    bool isLearned = Wugongs.Exists(element => element.Key == item.Skill);
                    if (isLearned)
                        return true;
```


> > > 可以交给我试着去解决这个bug么
> > 
> > 
> > 你可以验证下，我感觉是没问题的
> 
> 经测试，已经学会的武功，拳掌等属性未达标导致的无法修炼限制确实是忽略的。 但是，“仅XX可以修炼”条件未忽略。 比如六脉神剑，其他人如果改出来之后，再去装备秘籍会提示无法修炼。

* 这个是因为**[判断是否学会的逻辑]**在**[特定人物限制条件]**后面，把**[是否已经学会的逻辑]**挪到[L504]前就行了(https://github.com/jynew/jynew/blob/main/jyx2/Assets/Scripts/GameSave/RoleInstance.cs#L504)
```CSharp
               /*
                    在这先判断有没有学会
               */

                if ((int)item.ItemType == 2)
                {
                    //有仅适合人物，直接判断
                    if (item.OnlySuitableRole >= 0)
                    {
                        return item.OnlySuitableRole == this.Key;
                    }

                    //内力属性判断
                    if ((this.MpType == 0 || this.MpType == 1) && (item.NeedMPType == 0 || (int)item.NeedMPType == 1))
                    {
                        if (this.MpType != (int)item.NeedMPType)
                        {
                            return false;
                        }
                    }
                }
```

**Comment by FengQi777** [comment]
已完成更改，经过测试，学会的武功可直接装备对应秘籍
学满武功可以继续装备不能获得技能的秘籍，如霹雳秘籍等
但无法装备可以获得新技能的秘籍
pr已经提交
