### ISSUE TITLE
能否升级Unity编辑器到2021.3 LTS以上？

### ISSUE THREAD

**Issue by yunhailuo** [jynew/jynew#1328]
首先非常感谢众位大佬用爱发电！

提这个需求主要是想在Linux环境尝试，而2020的LTS没有Linux编辑器。我也自己尝试过一下，从导入和构建来说貌似需要一些手动更新：
- Rewired插件需要更新，否则会有[这样的报错](https://guavaman.com/projects/rewired/docs/Troubleshooting.html#compiler-errors-after-upgrading-unity)。
- Odin inspector插件也需要更新。但是也可以通过删除一个`Sirenix.Utilitie`绕过[`LinqExtensions.ToHashSet`的问题](https://odininspector.com/patch-notes/3-0-9-0)。
- 删除额外引入的Newtonsoft JSON插件。

但是我完全不确定这样升级之后有没有问题，也不知道该如何完整地测试；更主要的是不确定关于升级编辑器的政策是怎样的，会不会对项目开发产生不良影响。请大佬指点🙏

**Comment by chenggongchina** [comment]
理论上应该可以升级，在影响原有流程的话可以升级。
升级完成自测后可提交一个PR，我们会再安排进行一下测试，没有问题的情况下可以合并入主干。

**Comment by yunhailuo** [comment]
多谢指点！不好意思，在尝试却忘记回复了🤦 找了一台Windows11尝试，貌似可以。我自己测试一下再提交PR。
