### ISSUE TITLE
安卓端，游戏设置没有保存，重启游戏后被还原

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#1349]

**Comment by chenggongchina** [comment]
![72VJFNNXP0 W@%LGOI 7E](https://user-images.githubusercontent.com/7448857/204844189-4f388641-d8d3-4ede-a491-60987226e026.png)
此处没有申请权限，这块权限申请要做得更友好点。。。

**Comment by 0kk470** [comment]
emmmmm，之前没考虑到Android端，现在必须动态申请相关权限了？

**Comment by 0kk470** [comment]
看了下日志，在启动mod时会获取文件相关权限，应该没问题。
异常主要报在json插件反序列化那

**Comment by 0kk470** [comment]
拉了下代码发现申请Android权限的代码注掉了，所以是每次文件读写都要手动搞个弹窗通知下用户然后申请权限？

**Comment by 0kk470** [comment]
> 

不生效的bug确认是插件版本导致的

**Comment by chenggongchina** [comment]
移动端出于权限保护的考虑，修改为使用PlayerPrefs保存配置
