### ISSUE TITLE
求大佬添加一键出包脚本、工具，方便进行出包观察效果和测试游戏

### ISSUE THREAD

**Issue by XINCGer** [jynew/jynew#140]
求大佬添加一键出包脚本、工具，方便进行出包观察效果和测试游戏

**Comment by chenggongchina** [comment]
accpet，应该包括windows/android的出包流程

**Comment by official-minister** [comment]
现在可以编出安卓版本吗？想在手机上测一下

**Comment by chenggongchina** [comment]
可以，但是我还没写一键出包脚本。自己build即可，要把addressable的输出和引用地址改一下
