### ISSUE TITLE
武器有两把时，装备一把后另一把也失效

### ISSUE THREAD

**Issue by LCUchen** [jynew/jynew#1400]
在无际坊抽中了两把无际剑，然后给一个角色装备之后，另一个角色再想装备时，武器栏没有无际剑的选项了。
![image](https://user-images.githubusercontent.com/32902037/206397014-c7b2df0d-99f4-46a9-9bec-4e5d42be6d74.png)
![image](https://user-images.githubusercontent.com/32902037/206397620-2f41f0f0-f578-4b5b-897e-eeeb7855d4c1.png)

**Comment by armodeniz** [comment]
这个🗡是可以有俩的吗？会不会抽到两把剑其实是个bug
