### ISSUE TITLE
肉鸽 战斗中卡住

### ISSUE THREAD

**Issue by viruscamp** [jynew/jynew#1421]
两次战斗，敌方最后剩 铁头人，没有战斗动作了，还有空闲动作，可以缩放，拖动

**Comment by LCUchen** [comment]
![image](https://user-images.githubusercontent.com/32902037/208250714-e352b207-abe6-4cca-aab3-58030c704dfa.png)
感觉是敌方没有内力了，然后一直卡着

**Comment by 0kk470** [comment]
表现相关的延时逻辑访问已销毁对象导致在战斗循环里抛异常从而卡死的问题
![image](https://user-images.githubusercontent.com/25216715/209514184-92af6bd8-3c3b-403d-bdf5-009825d77b63.png)
