### ISSUE TITLE
plus版本 收虚竹后进少林寺虚竹消失，带石破天去侠客岛无法触发剧情，倚天剧情无法触发杀成昆

### ISSUE THREAD

**Issue by Jinyongmi** [jynew/jynew#1422]
plus版本 收虚竹后进少林寺虚竹消失，带石破天去侠客岛无法触发剧情，倚天剧情无法触发杀成昆

目前玩到现在发现的问题，导致游戏无法继续。

**Comment by MephistoSatanDevil** [comment]
金庸群侠传3D Plus版不是本项目内容，请找MOD作者进行反馈。

**Comment by viruscamp** [comment]
都是正常的，你的问题
1. 原版就是，收虚竹后不能回少林
2. 你有赏善罚恶令吗？
3. 明教分舵 明教总舵 接找狮王任务 灵蛇岛 冰火岛 杀成昆任务
