### ISSUE TITLE
为以后扩展开发考虑，可否增加“六边形战斗格子”支持？

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#145]
不是更改，只是增加这种选择，类似即时制战斗模式的支持方式。
也是与原作的续作（侠客风云传、侠客风云传前传及河洛群侠传）的战斗格子趋同。

**Comment by chenggongchina** [comment]
本来做了，被我删了。有兴趣的人可以再写一遍，现在不并入版本必须需求

**Comment by chenggongchina** [comment]
应该只需要在现在的基础上略微修改即可做到
