### ISSUE TITLE
玩家：3d重置版问题报告

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#1469]
您好！
我试玩了三遍3d重置版，感觉不错。但有以下两点，始终有问题，可能是bug。
1.瑛姑剧情：不杀一灯后，去找老顽童，再去黑龙潭跟瑛姑、老顽童交谈，老顽童说记得去百花谷找他学左右互搏，结果我去百花谷始终见不到任何人，去黑龙潭找瑛姑和老顽童，以及去一灯居找一灯，对话不变，却始终没有看到他们三人在百花谷出现。之后去拿到了神雕侠侣，桃花岛找过郭靖，百花谷还是没人。后来一路玩下去，不知道什么时候，突然去一灯居发现一灯说话不一样了，然后去百花谷发现他们三人终于出现在百花谷。这究竟是为什么呢，看很多攻略说解决完瑛姑事件不杀一灯就能去百花谷学左右互搏了。
2.林平之剧情，击败青城派，找侯人雄获知消息后去通知林平之，然后邀请他加入，无论是第一次拒绝邀请，第二次再邀请也好，道德高、低也好，都不能得到辟邪剑谱。虽然这个剑谱并没有什么用，但也是非常奇怪。

以上问题特报，希望能在更新中解决。

谢谢！

**Comment by qige2016** [comment]
据说中途不能存档

**Comment by armodeniz** [comment]
辟邪剑谱这个应该已经解决了啊，这人是不是玩的老版本

**Comment by MephistoSatanDevil** [comment]
不仅没说清楚是哪个版本而且他也没说清楚是哪个MOD

**Comment by beibiaoji** [comment]
运行不了啊，提示steam没有启动或登录

**Comment by MephistoSatanDevil** [comment]
> 运行不了啊，提示steam没有启动或登录，mode加载出错了，请检查文件是否损坏

那你是从Steam启动的么？

**Comment by beibiaoji** [comment]
Unity运行

**Comment by beibiaoji** [comment]
> 
clone 下来Unity运行不了

**Comment by WaterSweet** [comment]
> 运行不了啊，提示steam没有启动或登录，mode加载出错了，请检查文件是否损坏

我也是遇到相同的问题，clone下来提示登陆steam，是需要从steam上下载资源mod吗？
