### ISSUE TITLE
群侠世界 - 百花谷

### ISSUE THREAD

**Issue by MikeG369** [jynew/jynew#1476]
把周伯通带到黑潭与瑛姑相见后，周伯通没有回到百花谷。因此不能学到左右互搏术。

一灯大师也一直说真希望瑛姑来把他杀了。

**Comment by xuyuanxiang** [comment]
我也遇到同样的问题。未开启任何作弊模式，就是正常游玩。

我拿到《神雕侠侣》的天书后，才开始走射雕的剧情。

我在百花谷告诉老顽童他有儿子后，回到黑龙潭瑛姑小屋。

我觉得BUG可能出在这里：
 由于着急学左右互搏，我**没有先跟瑛姑对话**，而是先跟老顽童对话，对话内容已经让我以后去百花谷找到学左右互搏。
 之后才跟瑛姑对话，再跟老顽童对话。

出黑龙潭后，去百花谷只有蜜蜂箱，而没有老顽童。

之后我再回黑龙潭，发现小屋里瑛姑和老顽童也消失了。
