### ISSUE TITLE
v0.2stable版本还差两本书，是不是bug

### ISSUE THREAD

**Issue by fr0zenrain** [jynew/jynew#1485]
5.1人太多，不敢出去玩，测试了一把游戏，真的是第一次玩。还差射雕和笑傲。最后输指令开了软猬甲和霹雳刀法，中途没输过其他指令。看网上的攻略，我应该是嵩山大战后没拿到率意帖，卡在梅庄了。另外黑龙潭也卡住了，进去无法动弹。不管有没有程英。这个是bug么。

**Comment by qige2016** [comment]
应该是bug，最好steam搜《群侠传，启动！》玩最新版本

**Comment by fr0zenrain** [comment]
一个已解决，到打东方不败了，有点强。只剩下一本了

**Comment by fr0zenrain** [comment]
我玩的Android版，目前只剩下黑龙潭问题。
