### ISSUE TITLE
将Unity3D 升级到支持Silicon的版本，例如2021.3.26f1或者2022.3.0

### ISSUE THREAD

**Issue by birdinforest** [jynew/jynew#1490]
如题。
目前的Unity3D版本在Silicon的Mac上性能有问题，每次修改代码后重新载入的时间很长。
能否考虑升级到支持Silicon的版本。

尝试了一下升级2021.3.26f1。好像需要修改的东西不多：

1. 升级程序自动修改`jyx2/Assets/Plugins/Easy Save 3/Scripts/ES3Prefab.cs`
```csharp
#if UNITY_2018_3_OR_NEWER
-            if (this.gameObject.scene.name != null || UnityEditor.Experimental.SceneManagement.PrefabStageUtility.GetCurrentPrefabStage() != null)
+            if (this.gameObject.scene.name != null || UnityEditor.SceneManagement.PrefabStageUtility.GetCurrentPrefabStage() != null)
#else
             if (this.gameObject.scene.name != null)
#endif
```

2. `jyx2/Assets/Editor/BuildTools/Jyx2ModTool.cs` 需要手动更改一行代码
```csharp
-            var allBundles = AssetDatabase.GetAllAssetBundleNames().ToHashSet();
+            var allBundles = System.Linq.Enumerable.ToHashSet(AssetDatabase.GetAllAssetBundleNames());
```

3. xLua升级到[Tag:v2.1.16_with_silicon_support](https://github.com/Tencent/xLua/releases/tag/v2.1.16_with_silicon_support)

4. 升级程序修改了很多mat和png.meta文件

**Comment by 0kk470** [comment]
貌似有个[pr](https://github.com/jynew/jynew/pull/1348)升级了版本，可以尝试下？没问题可以让仓库主merge掉。

**Comment by chenggongchina** [comment]
那个pr好像修改了大量的逻辑代码，如果只是修改少量代码，题主可以提交一个pr
需要在各个真机平台都打包测试下，没问题方可merge

**Comment by birdinforest** [comment]
> 貌似有个[pr](https://github.com/jynew/jynew/pull/1348)升级了版本，可以尝试下？没问题可以让仓库主merge掉。

@yunhailuo 的PR考虑地更全面。关闭这个Issue。
