### ISSUE TITLE
git clone 本地失败

### ISSUE THREAD

**Issue by GGboy777** [jynew/jynew#1498]
想克隆到本地，但是可能是项目太大了，每次**克隆到一半**就失败了。
然后尝试下载压缩包，完全下载之后，解压文件显示**文件末端错误**。
有vpn和无vpn环境都试过了，非常难受。
![image](https://github.com/jynew/jynew/assets/93924492/524b8c27-47d2-4fc6-b5ba-f82c864ad645)

**Comment by chenggongchina** [comment]
目前项目是比较大，建议找一个比较稳定的梯子。
