### ISSUE TITLE
显示MOD导入失败，各种报错。

### ISSUE THREAD

**Issue by GitHubJKin** [jynew/jynew#1499]
![image](https://github.com/jynew/jynew/assets/20738043/d4487832-e12a-4842-b28e-7edf6dc82ba3)
是git clone下载的，重下了几次都提示没有手动生成XLua代码，可能导致载入Mod出错。请查看项目手册！
这哪有什么这个相关的问题解决方法？刚入门学习unity

**Comment by wrj19960514** [comment]
![UYDLQH~CJEFDNFC4$ BJQSQ](https://github.com/jynew/jynew/assets/52058829/25a0af46-3307-42b8-9a80-3d170a180cc1) 
generate code

**Comment by wrj19960514** [comment]
xlua generate code
![QQ图片20240122165814](https://github.com/jynew/jynew/assets/52058829/b9208fe6-3250-4059-b792-6ac85398d32c)

**Comment by wrj19960514** [comment]
https://www.bilibili.com/video/BV1Gr4y1E7VC/?spm_id_from=333.999.0.0&vd_source=0dadc0107d123b7a701509b1ea5469ef
https://www.bilibili.com/video/BV1NN4y1T7v4/?spm_id_from=333.999.0.0&vd_source=0dadc0107d123b7a701509b1ea5469ef

**Comment by wrj19960514** [comment]
https://www.bilibili.com/video/BV1Gr4y1E7VC/?spm_id_from=333.999.0.0&vd_source=0dadc0107d123b7a701509b1ea5469ef
https://www.bilibili.com/video/BV1NN4y1T7v4/?spm_id_from=333.999.0.0&vd_source=0dadc0107d123b7a701509b1ea5469ef
https://www.bilibili.com/video/BV1iB4y1v7ir/?spm_id_from=333.999.0.0&vd_source=0dadc0107d123b7a701509b1ea5469ef
