### ISSUE TITLE
加载游戏时报错Lua对象为空

### ISSUE THREAD

**Issue by zayngdev** [jynew/jynew#162]
![image](https://user-images.githubusercontent.com/49690096/121614942-61379280-ca92-11eb-83ae-e19bb242ccf8.png)

**Comment by zayngdev** [comment]
关闭项目，重新加载后，错误消失， 在这里记录一下。

**Comment by eaphone** [comment]
可以描述一下具体场景

**Comment by zayngdev** [comment]
就是游戏初始运行之后，会出现前两个错误， 加载场景到89% 的时候会出现后两个错误， 然后就卡在那里了

**Comment by chenggongchina** [comment]
清空一下luawrap（应该是你本地情况，luaWrap文件过期了）
以及重新GENDATA后运行游戏。

**Comment by chenggongchina** [comment]
不是问题，如果有特殊其他原因请继续OPEN
