### ISSUE TITLE
角色的动作制作

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#21]
目前制作角色的待机和技能动作即可，位于art/Animations

**Comment by chenggongchina** [comment]
需要确定动作制作登记表，
管理外包/付款/验收/入库/配置

**Comment by sujizhang** [comment]
技能制作流程更新在wiki里，链接如下。希望各路大神前来认领技能动作表。

[金庸群侠传3D重制版 战斗技能制作须知]
(https://github.com/jynew/jynew/wiki/%E9%87%91%E5%BA%B8%E7%BE%A4%E4%BE%A0%E4%BC%A03D%E9%87%8D%E5%88%B6%E7%89%88-%E6%88%98%E6%96%97%E6%8A%80%E8%83%BD%E5%88%B6%E4%BD%9C%E9%A1%BB%E7%9F%A5)

**Comment by chenggongchina** [comment]
已经全部完成
