### ISSUE TITLE
战斗格子相关逻辑重构

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#215]
重构方向是：

1、每个战斗场景里直接生成格子（建议直接在场景的 Level/BattleBlocks下）
2、需要能够在Editor里方便的编辑格子（新增、删除）

其他可以补充

现在的流程：https://www.bilibili.com/video/BV1mz4y117j3?p=7

**Comment by sclong02** [comment]
自己的锅，自己认领。。。
