### ISSUE TITLE
可视化编辑流程

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#218]
增加可视化剧情编辑流程，集成xnode

**Comment by chenggongchina** [comment]
![20210626jyx2NodeGraph_compress](https://user-images.githubusercontent.com/7448857/123508826-57be4500-d6a4-11eb-9c1a-0bf72ce6b615.gif)

还未实现逻辑

**Comment by chenggongchina** [comment]
基础框架已经实现完毕，待实现剩下的节点，待补充文档。

**Comment by chenggongchina** [comment]
![AS8)}(1C I{%39C)GJ1O$32](https://user-images.githubusercontent.com/7448857/123520478-8c9dbc80-d6e3-11eb-857c-09d522f2c316.png)
![4XRT4O9%3{FWB K @ 0%R@3](https://user-images.githubusercontent.com/7448857/123520479-8dcee980-d6e3-11eb-8b6d-72a3a94aed10.png)
![_ Z21ZS0@0(NW)%$PYH9$DF](https://user-images.githubusercontent.com/7448857/123520481-8f98ad00-d6e3-11eb-9011-4368d6430f58.png)
![MQ$8J1%(67CAVE5HQM4DPHG](https://user-images.githubusercontent.com/7448857/123520484-91627080-d6e3-11eb-9b04-91644de536f9.png)
![~3F(4ES 0KN%A_)RTUZSFQT](https://user-images.githubusercontent.com/7448857/123520488-93c4ca80-d6e3-11eb-844d-506aa15ca111.png)

**Comment by chenggongchina** [comment]
https://user-images.githubusercontent.com/7448857/123583843-e18c2080-d812-11eb-89bd-efdc107b5a5b.mp4

**Comment by chenggongchina** [comment]
https://user-images.githubusercontent.com/7448857/123583865-ecdf4c00-d812-11eb-9842-f78e59af7e20.mp4

**Comment by chenggongchina** [comment]
![1624856952_clip](https://user-images.githubusercontent.com/7448857/123584039-4182c700-d813-11eb-8bfb-21bc5c5e0e9c.gif)

**Comment by zyjdxtc** [comment]
节点添加完毕。少许函数本身尚待实现或修改。(Judge14BooksPlaced, FightForTop, EndAmination, JudgeScenePic)
