### ISSUE TITLE
缺少背手拿剑模型动作

### ISSUE THREAD

**Issue by dagangfanyu** [jynew/jynew#225]
缺少拿剑模型动作
![image](https://user-images.githubusercontent.com/84125816/123656373-70745980-d862-11eb-8462-90b3583c5caa.png)
![image](https://user-images.githubusercontent.com/84125816/123657675-95b59780-d863-11eb-94f8-87f7a1b5c03a.png)

**Comment by eaphone** [comment]
close by #311
