### ISSUE TITLE
需要增加在离开事件上绑定触发事件的功能

### ISSUE THREAD

**Issue by chenerpang815** [jynew/jynew#233]
原因：
原版的一些事件，需要玩家再次进入触发的，会把触发器加在离开场景的位置，玩家触发时必定离开了。
我们现在是有按键离开的，但是事件提前触发了，结果显得怪异。
例子：
神雕山洞，一开始进入时雕蛇大战，再一次进入时雕在杨过边上了。但是现在的做法，还没离开，雕就回到杨过边上了。如果玩家回个头，就会觉得很怪异。

**Comment by chenggongchina** [comment]
想了下这个还是不改了，因为改起来要影响的地方不少。。。
其实这个怪异玩家应该是可以接受的。。
