### ISSUE TITLE
少林寺缺少洗髓经模型

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#237]
![image](https://user-images.githubusercontent.com/22126740/124360339-d6465400-dc5b-11eb-8bf7-dd2618fdabaa.png)
暂用图片替代

**Comment by HYYellowOne** [comment]
场景中添加洗髓经模型
![image](https://user-images.githubusercontent.com/51065949/131700780-0274b967-aea2-49db-ada1-9850626ce6a8.png)
