### ISSUE TITLE
成昆模型优化以及角色预设的制作

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#257]
成昆模型配色与原版差异稍大，建议优化。目前衣服为蓝红黑
![image](https://user-images.githubusercontent.com/22126740/125233899-1f5c6f00-e312-11eb-8245-a8ac55a8fa3e.png)

参考原型，改为黑色调为主
![image](https://user-images.githubusercontent.com/22126740/125233887-18356100-e312-11eb-832b-39f882f2c0fd.png)

**Comment by chenggongchina** [comment]
![image](https://user-images.githubusercontent.com/7448857/132089847-eac8d02d-6cba-4819-b735-27378c1882e0.png)
略作调整
