### ISSUE TITLE
缺少地道入口

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#259]
包括以下场景，地道入口逻辑已经实现。但是缺少地道入口模型
12_明教分舵，15_沙漠废墟，55_梅庄，76_霹雳堂
参考原型，显示往下走的楼梯：
![image](https://user-images.githubusercontent.com/22126740/125236104-005fdc00-e316-11eb-84ea-8386f9d94bde.png)

**Comment by HYYellowOne** [comment]
地形不好挖洞，只能先用黑色入口代替
![image](https://user-images.githubusercontent.com/51065949/132095737-53398758-c63a-4de4-840d-e93ca2fc7a73.png)
