### ISSUE TITLE
写个程序批量删除已经丢失的脚本

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#260]
特别是在各个场景的Player上，还有各种NPC上。

![F%RPM RN59X YM HW ACGL](https://user-images.githubusercontent.com/7448857/125294688-104be000-e357-11eb-9c87-927ad7d8037d.png)

**Comment by zxsean** [comment]
我找个时间处理吧.

**Comment by zxsean** [comment]
可以关了
