### ISSUE TITLE
62_破庙缺少 挖开古墓动作的timeline

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#273]
![image](https://user-images.githubusercontent.com/22126740/125810022-f4ee688b-0190-4616-be4a-527c3bd0a720.png)
参考原型：
![image](https://user-images.githubusercontent.com/22126740/125810138-6f2d8da0-6c20-4465-8ee9-8e5970c740d8.png)

**Comment by HYYellowOne** [comment]
添加墓堆和挖开墓堆模型
![image](https://user-images.githubusercontent.com/51065949/132220015-936a2b29-d95d-47a9-baf1-fe525c7ffa98.png)

**Comment by chenggongchina** [comment]
可以装配一下

**Comment by chenggongchina** [comment]
已经装备，还没有挖的动作。

**Comment by chenggongchina** [comment]
需要制作一个挖地的动作

**Comment by 357197596** [comment]
铲子挖地动作已经传了
