### ISSUE TITLE
源码一键打包Android报错

### ISSUE THREAD

**Issue by RayKuCha** [jynew/jynew#278]
Assets\Scripts\Jyx2ResourceHelper.cs(23,19): error CS0234: The type or namespace name 'AddressableAssets' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

Error building Player because scripts had compiler errors
![QQ图片20210718164545](https://user-images.githubusercontent.com/42938527/126061313-90bd90fa-7fd2-4c10-af18-c35455a6d168.png)

**Comment by zxsean** [comment]
我处理下

**Comment by RayKuCha** [comment]
@zxsean 谢谢大佬帮忙解决
