### ISSUE TITLE
反序列化配置表异常，文案错误

### ISSUE THREAD

**Issue by Leii** [jynew/jynew#281]
![QQ20210718-0](https://user-images.githubusercontent.com/11715405/126068028-e587c6b0-27ee-4c9b-88e3-f174255736f2.png)

![屏幕快照 2021-07-18 下午7 48 00](https://user-images.githubusercontent.com/11715405/126068040-072f9c4b-0b05-4007-aacc-dde1e7827b1e.png)

Gendata已从Tools移到配置表

**Comment by zxsean** [comment]
这是lib文件. 库里面没有. 需要lib所有者修改一下.

**Comment by chenggongchina** [comment]
重构了，不再需要gendata
