### ISSUE TITLE
开局事件ID解析错误Bug

### ISSUE THREAD

**Issue by RayKuCha** [jynew/jynew#293]
![QQ截图20210721205657](https://user-images.githubusercontent.com/42938527/126493716-1773b6ce-417b-4de3-9596-94492367a3c7.png)
![QQ截图20210721210529](https://user-images.githubusercontent.com/42938527/126493724-fd6cd9d8-8305-4274-9a1d-d8b3d36bf8c6.png)

**Comment by eaphone** [comment]
最新版本应该不存在这个问题。
