### ISSUE TITLE
装备提升属性装备使属性达到最大时，升级无法提升属性

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#317]
人物攻击为80，准备玄铁剑，使人物攻击提升为100.
这时候人物升级时，人物本身攻击不会再提升。

期待结果是，人物本身属性没达到100，还可以提升，只是提升后装备武器人物攻击力依然只有100

**Comment by chenggongchina** [comment]
考虑下是否有更优的实现方式，而不是直接去修改一个存档数值。比如在获取攻击力的时候不是使用Attack，而是封装一个GetAttack(bool isOrigin)的函数实现？

**Comment by centauruszzz** [comment]
> 考虑下是否有更优的实现方式，而不是直接去修改一个存档数值。比如在获取攻击力的时候不是使用Attack，而是封装一个GetAttack(bool isOrigin)的函数实现？

可是很多访问是直接通过role. Attack来进行的，怎么能追踪到他们

**Comment by eaphone** [comment]
#356
