### ISSUE TITLE
冰火岛缺少事件

### ISSUE THREAD

**Issue by qige2016** [jynew/jynew#33]
![QQ截图20210523145634](https://user-images.githubusercontent.com/18051955/119251088-31097c00-bbd7-11eb-821b-44c3641fff90.png)
![QQ截图20210523145645](https://user-images.githubusercontent.com/18051955/119251091-336bd600-bbd7-11eb-81bc-24995054559a.png)

**Comment by qige2016** [comment]
缺少事件0

**Comment by Leo-YJL** [comment]
这个0和1是同一个事件，在Unity里面只要一个就行了

**Comment by qige2016** [comment]
> 这个0和1是同一个事件，在Unity里面只要一个就行了

好的
