### ISSUE TITLE
PC版，侠客按钮下，左边的队友血量显示带着公式，一长串字符

### ISSUE THREAD

**Issue by yujingsuifeng** [jynew/jynew#352]
进入战斗后能够显示阳内颜色，也就是orange。
侠客按钮之下，标记颜色的一串字符大概是：<color=white>（后面看不到了）。

**Comment by eaphone** [comment]
无法复现。请更新代码到最新，重新打包测试

**Comment by yujingsuifeng** [comment]
我用的20210809-021526这个版本也有这个问题，是昨天最新的代码。等今天新的版本出来我再试试。

**Comment by eaphone** [comment]
无法复现。貌似你的版本有问题
