### ISSUE TITLE
燕子坞，给慕容复两件道具后，段誉应该站在王语嫣旁边

### ISSUE THREAD

**Issue by yujingsuifeng** [jynew/jynew#355]
当前版本中，给完两件道具后，段誉就回到队伍了（给慕容复第一件道具的时候，段誉出现在了王语嫣旁边）。

**Comment by eaphone** [comment]
这个不算bug。之前的设计，为了让 对话没那么太突兀。npc说话时会让他显示。
所以段誉说话时，脚本使段誉显示了。对话结束后就消失了。跟给第几件道具没关系。
原作，只要燕子坞对话了，段誉在队里，在离开燕子坞时段誉就会离队。
