### ISSUE TITLE
九阳神功升级时，人物生命会明显恢复

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#368]
重现步骤：
人物修炼九阳神功，
战斗中让人物生命下降到较低状态
结束战斗时，如果九阳神功升级，人物没升级情况下，人物生命会明显恢复。
期待结果：人物最大生命提升，但人物生命不变化（待确认）

**Comment by chenggongchina** [comment]
需要确认一下具体战斗后恢复的逻辑
