### ISSUE TITLE
20210821测试问题

### ISSUE THREAD

**Issue by sankongjin** [jynew/jynew#377]
段誉首次战斗默认待机佩戴刀
冰火岛外景没有山
暗器伤害计算的有问题，田伯光和胡斐这种擅长暗器的打出来基本没伤害
使用暗器在战斗中不消耗
神雕洞的蛇缺头像
原著里每场战斗结束会增加部分HPMP，是否考虑优化？

**Comment by chenggongchina** [comment]
建议之后把问题拆成多个，这样可以逐个修复并对应提交编号。

**Comment by chenggongchina** [comment]
段誉首次战斗默认待机佩戴刀==》无法复现

**Comment by chenggongchina** [comment]
重新paint冰火岛
![image](https://user-images.githubusercontent.com/7448857/132532690-662b1ddd-1c7d-439d-b9db-766388ad6d31.png)

**Comment by chenggongchina** [comment]
其他问题暂时不考虑优化了。
