### ISSUE TITLE
船体穿模

### ISSUE THREAD

**Issue by trhfghjr** [jynew/jynew#389]
上船后航行靠近岸边，船体一半与陆地模型重合，下船正常切换地图后发现船体与陆地模型重合，可以移动，但是无法返回海上

**Comment by chenggongchina** [comment]
请给个具体复现的地方的动图或者截图

**Comment by trhfghjr** [comment]
> 请给个具体复现的地方的动图或者截图

![image](https://user-images.githubusercontent.com/13475640/133038288-5384b34a-b49b-4c0a-9694-d07e113bcbf7.png)
