### ISSUE TITLE
返回主菜单不能正常执行

### ISSUE THREAD

**Issue by XiuMingLin** [jynew/jynew#407]
![image](https://user-images.githubusercontent.com/33442682/132624219-9384ca6c-2813-4cf1-95b3-45c0623a5841.png)
![image](https://user-images.githubusercontent.com/33442682/132624063-e3da12fa-c54b-4e21-8f43-b9efba1bd7e8.png)

**Comment by XiuMingLin** [comment]
在Unity中运行没有问题，打Windows包会出现

**Comment by chenggongchina** [comment]
已经修复
