### ISSUE TITLE
给老顽童蜜不出蜂箱

### ISSUE THREAD

**Issue by lokxbd** [jynew/jynew#416]
![Screenshot_2021-09-12-18-03-30-149_com jynew jyne](https://user-images.githubusercontent.com/63410009/132983522-7972840b-f85f-4a41-b3ba-3765eed4714b.jpg)
![Screenshot_2021-09-12-18-03-08-458_com jynew jyne](https://user-images.githubusercontent.com/63410009/132983528-66584d54-940c-45a3-8d81-324a869b9e1a.jpg)
随后强行传送进入绝情谷底，做完杨过小龙女任务后，再去黑龙潭，瑛姑不在，不知道是否有联系

**Comment by qige2016** [comment]
使用玉蜂浆后，要去百花谷门口才能触发事件。

**Comment by lokxbd** [comment]
已出入百花谷多次

**Comment by qige2016** [comment]
我刚刚又试了一遍流程，没啥问题。方便的话可以录个视频，把版本号带上

**Comment by lokxbd** [comment]
![Screenrecorder-2021-09-13-15-12-21-512 00_00_06-00_00_34~1 00_00_00-00_00_30](https://user-images.githubusercontent.com/63410009/133042572-9c408a17-08f2-456b-9879-84e9d472b576.gif)
版本20210910

**Comment by qige2016** [comment]
这个bug9月10日下午才合进去，可以测试下现在最新版本还复现不

**Comment by lokxbd** [comment]
好了已经

**Comment by lokxbd** [comment]
好了已经
