### ISSUE TITLE
非主角战斗模型显示主角

### ISSUE THREAD

**Issue by qige2016** [jynew/jynew#433]
![N6 2H@_5LD04K2Q`UVP_X%Q](https://user-images.githubusercontent.com/18051955/134096838-33606c50-4742-427d-ad7e-53d28b1948e3.png)
![}_4(9%UJA @KMAOS@0M}I20](https://user-images.githubusercontent.com/18051955/134097046-9463c26a-1817-43da-b52d-6fd64c482d68.png)

**Comment by eaphone** [comment]
duplicated by #456 
close by #458
