### ISSUE TITLE
功能：存档同步

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#44]
期待结果 ：接入onedrive, baiduyun网盘，登陆账号后，实现多平台，多终端存档同步

**Comment by MephistoSatanDevil** [comment]
能否考虑最终成品以免费游戏的方式发布于Steam平台，利用Steam平台的云存档功能实现？

**Comment by chenggongchina** [comment]
> 能否考虑最终成品以免费游戏的方式发布于Steam平台，利用Steam平台的云存档功能实现？

这样发布是违法的，因为本游戏并未取得授权。
