### ISSUE TITLE
不论在场景中还是大地图中，方向键绕三分之二周，自动跳出调试窗口。

### ISSUE THREAD

**Issue by Yd791129170** [jynew/jynew#445]
不论在场景中还是大地图中，方向键绕三分之二周，自动跳出调试窗口。
![003](https://user-images.githubusercontent.com/91588574/135213798-9d3f6cf8-81e0-4f86-a408-460f069ce4f6.jpg)

**Comment by chenggongchina** [comment]
请标题写明BUG具体的情况

**Comment by eaphone** [comment]
这个貌似是第三方库 Reporter窗口。安卓版必现
