### ISSUE TITLE
【bug】昆仑仙境的传输位置错误

### ISSUE THREAD

**Issue by xtom0369** [jynew/jynew#449]
![LS60X~268(ZZ}W34D5OP}}4](https://user-images.githubusercontent.com/25240405/135588821-e2a80af5-691f-4601-bced-b06db78eaa4d.png)

**Comment by eaphone** [comment]
选错位置了。
泥土中控制台选择的昆仑仙境是trigger。应该从左边的“选择场景” 下拉框里选择。
