### ISSUE TITLE
【优化】图片中武当山内有一道空气墙

### ISSUE THREAD

**Issue by xtom0369** [jynew/jynew#450]
![image](https://user-images.githubusercontent.com/25240405/135596328-8f4e7416-d631-4759-83fa-645d88f1f5e2.png)

**Comment by eaphone** [comment]
![image](https://user-images.githubusercontent.com/22126740/135738931-326da500-033a-48f0-b713-aedd4e4fa8e5.png)
调整空气墙到后面
