### ISSUE TITLE
【bug】满足条件却不能修炼九阳真经

### ISSUE THREAD

**Issue by xtom0369** [jynew/jynew#452]
![`%2YHHKSH(4AT`RA2881Q%2](https://user-images.githubusercontent.com/25240405/135622204-59d494cf-ef2e-4e91-9d27-cf83498553ae.png)
![B0}2@M97`1S 15R43R41}Q6](https://user-images.githubusercontent.com/25240405/135622251-d5819cb4-fb8c-4a7e-8b2d-d47766ddbb37.png)

不知道和我把张无忌放回去了有没有关系

**Comment by eaphone** [comment]
你的内力是阴性（内力显示为紫色），九阳神功要求阳性（物品名称显示为黄色）。
你需要修炼18泥偶或者易筋经之类的容内力变为中心（白色）才能修炼
