### ISSUE TITLE
【bug】GM指令打开韦小宝商店报错

### ISSUE THREAD

**Issue by xtom0369** [jynew/jynew#457]
![image](https://user-images.githubusercontent.com/25240405/135701845-d97a7032-5ef0-447d-8e1a-cc72aa1a53f8.png)

使用指令WeiShop()报错

**Comment by eaphone** [comment]
非正常用户场景。不建议这样做。
测试需要什么物品，可以直接通过控制台 item {number} 指令获取。

**Comment by xtom0369** [comment]
顺手加个判断和提示而已，现在直接打开会报错，看了代码才知道，减少非技术人员的心智负担

**Comment by xtom0369** [comment]
建议完善下wiki备注，我这边修改不了 https://github.com/jynew/jynew/wiki/%E6%B8%B8%E6%88%8F%E4%BA%8B%E4%BB%B6%E6%8C%87%E4%BB%A4

**Comment by eaphone** [comment]
close by #464
