### ISSUE TITLE
【梳理代码】统一大地图判断接口

### ISSUE THREAD

**Issue by xtom0369** [jynew/jynew#460]
1. 当前大地图判断方式较多，有判断m_CurrentType的，有判断mapId是否为空的，有直接判断Tag的，可统一为一个IsWorldMap属性，减少疑惑。

2. m_CurrentType的判断为Tag是否包含BigMap，但是配置表中为WORLDMAP，看着为残留，一并整理

**Comment by chenggongchina** [comment]
额，没有提交pull request？

**Comment by xtom0369** [comment]
提交了，昨天出去耍之前发现有bug把修改压本地了
