### ISSUE TITLE
药王庄门可以直接穿过去

### ISSUE THREAD

**Issue by qige2016** [jynew/jynew#480]
![image](https://user-images.githubusercontent.com/18051955/136734806-338c904b-01df-4d93-bb1b-d05b83d275e6.png)

**Comment by qige2016** [comment]
梅庄还有两处
![image](https://user-images.githubusercontent.com/18051955/136735752-f36e67e2-d290-40b7-bbf2-c2284e07db83.png)
![image](https://user-images.githubusercontent.com/18051955/136735845-4e728891-b74d-4a3c-a9be-d62c8e208fd5.png)

**Comment by qige2016** [comment]
擂鼓山有一处
![image](https://user-images.githubusercontent.com/18051955/136736278-12311085-e24a-4d14-b7a7-9612c6de1b54.png)

**Comment by eaphone** [comment]
nav mesh obstacle中勾选carve可以解决：
![(R%FM3BZC1$F(WTA80 1J](https://user-images.githubusercontent.com/22126740/136960358-8b78bf5b-59ae-4f14-8cb6-a9d1ad5e1fcb.png)
上图为carve勾选(左)和不勾选(右)对导航网格的影响
