### ISSUE TITLE
关于版本号的提示改进建议

### ISSUE THREAD

**Issue by XINCGer** [jynew/jynew#481]
RT，目前的版本号展示仅在登录界面有，建议在游戏中常驻显示，以便出现问题的时候，第一时间知道版本号
![1](https://user-images.githubusercontent.com/10908565/136747037-ecc87518-d255-4aa2-bf37-28c2a4f3caaa.png)

**Comment by eaphone** [comment]
goodidea

**Comment by eaphone** [comment]
e929427 fixed this issue
