### ISSUE TITLE
【bug】切换功法 属性下降

### ISSUE THREAD

**Issue by Yd791129170** [jynew/jynew#519]
主角或队友，切换修炼功法后，其属性会被扣减原修炼功法应得的功效。如：梯云纵改紫霄后，轻功减3；再改回梯云纵，内力减少10；一直切换，属性归零。
![1](https://user-images.githubusercontent.com/91588574/139611614-51cc68e9-d4fb-4c6d-a25f-52e7a7546778.jpg)
![2](https://user-images.githubusercontent.com/91588574/139611632-6bce85e7-9151-4aa4-af8c-e6b2e65b4e65.jpg)
![3](https://user-images.githubusercontent.com/91588574/139611654-85722674-9cae-41a8-b6df-398be9a5308e.jpg)
![4](https://user-images.githubusercontent.com/91588574/139611660-0828b3da-218e-4506-95d6-63f48232e3a5.jpg)

**Comment by qige2016** [comment]
@Yd791129170  #516 该pr已修
