### ISSUE TITLE
蜘蛛洞战斗卡战败界面

### ISSUE THREAD

**Issue by janehuang95** [jynew/jynew#565]
蜘蛛洞的战斗，战败后连续两次在【GAMEOVER读档界面】弹出对话框（覆盖在【GAMEOVER读档界面】上方），点击对话框后，又重新进入蜘蛛洞的战斗（这时全员空血，明显是已经进行过战败结算了），第三次之后才恢复正常

**Comment by eaphone** [comment]
这类问题出现在enterTrigger触发的战斗中，失败后会传送回触发点，并再次触发trigger导致lua处于执行中的状态。
