### ISSUE TITLE
部分场景无法使用鼠标移动

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#6]
进入场景无法使用鼠标移动人物，键盘可以移动人物
无法移动场所包括：天宁寺，山洞（待更新）

**Comment by chenggongchina** [comment]
可以查看下是否是因为navmesh导航网络没有设置

**Comment by chenggongchina** [comment]
参考资料：https://www.bilibili.com/video/BV1mz4y117j3?p=3


@eaphone

**Comment by eaphone** [comment]
需要把Bake中ground对应的layout设置为ground才能触发鼠标点击

![image](https://user-images.githubusercontent.com/22126740/119260784-eb64a780-bc06-11eb-8ab8-68b0ad7a18f7.png)
