### ISSUE TITLE
人物离队后物品未清除，再次加入时仍带有物品

### ISSUE THREAD

**Issue by kykdu** [jynew/jynew#601]
大部分人物第二次加入队伍时仍带有上次的物品，导致秘籍道具双份，比如段誉、田伯光等都如此。
应当是修复 #593 时引入的BUG

**Comment by kykdu** [comment]
修正：不是第二次加入，而是存读档后人物身上的物品就会重置，再次加入时仍能获得首次加入时的物品，想获得多少就能获得多少。
和队友是否在队无关，也就是说读档后再让队友离队然后马上加入，仍然可以获得物品。

**Comment by kykdu** [comment]
增加：队友离队时，如果有正在修炼的秘籍，会扣掉秘籍升级所增加的数值，比如刀剑暗轻类会扣对应数值，内功会扣对应生命内力攻防，反复操作可以扣到不能修炼该秘籍为止，轻功可以扣到0。

**Comment by qige2016** [comment]
版本号

**Comment by kykdu** [comment]
2021-11-23 10:50:03 +0800 
commit e5d9ba3397dafcbe5b9e41f5f3ede375e3ae84f6

**Comment by qige2016** [comment]
#602
