### ISSUE TITLE
武林大会请帖出问题

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#610]
网友描述

问题出现在拿完第十四本书（我最后一本拿的是桃花岛上的射雕，回家用的传送），回家后桌子上有武林大会的请帖，拿了直接卡在原地。传送后可以进出大小地图，但进行任何交互同样卡在原地，同时载入任何存档也是可以进出传送大小地图，但进行任何交互一样会卡住。退出游戏重开后问题消失，拿请帖还是卡住。
![X8%V3Q1JZVLRQ$QS(`5IJ3](https://user-images.githubusercontent.com/7448857/143515229-bbefd6c4-cc74-4a26-a358-bb954567494a.JPG)
[存档.zip](https://github.com/jynew/jynew/files/7605787/default.zip)

**Comment by qige2016** [comment]
和AllLeave()有关

**Comment by chenggongchina** [comment]
已修复
