### ISSUE TITLE
11月26日版：武功修炼后无法取下，提示“该角色不满足使用条件”

### ISSUE THREAD

**Issue by cooper436** [jynew/jynew#612]

**Comment by qige2016** [comment]
附上侠客页面

**Comment by cooper436** [comment]
![image](https://user-images.githubusercontent.com/62200838/143537741-08ffbb1e-a151-414a-a869-56ab50c76a62.png)

**Comment by cooper436** [comment]
![image](https://user-images.githubusercontent.com/62200838/143537983-f48788d3-b468-406c-b7d0-18697967481a.png)

**Comment by cooper436** [comment]
反复尝试，应该是逻辑问题，就是修炼满的武功不能直接取下，只能用其他武功替换修炼，但还是修改为可以卸下比较好

**Comment by qige2016** [comment]
确认满级武功判断有误

**Comment by chenggongchina** [comment]
已修复
