### ISSUE TITLE
收杨过拿不到玉峰浆，收林平之没有辟邪剑谱

### ISSUE THREAD

**Issue by lztitan** [jynew/jynew#616]
前者会导致剧情bug无法后续，而且非常奇怪的事情是，收了杨过再离队，他就回古墓了，（不是回山洞么？）

后者SL大法了好几次，都没有辟邪剑谱。

**Comment by qige2016** [comment]
#603 前者已修复

**Comment by qige2016** [comment]
#595 后者看此

**Comment by lztitan** [comment]
> #595 后者看此

我当时打福威镖局和青城派的时候还没有发现传送的功能，应该不是这个原因吧。。

**Comment by qige2016** [comment]
> 

和#603 原因一样

**Comment by lztitan** [comment]
> > 
> 
> 和#603 原因一样

谢谢大神，那我问下是不是这些等steam自动更新才能玩到正确版本？

**Comment by qige2016** [comment]
已经更新了
