### ISSUE TITLE
按下空格快捷键随机呼出页面

### ISSUE THREAD

**Issue by qige2016** [jynew/jynew#621]
检查下空格快捷键绑定

**Comment by chenggongchina** [comment]
原因不是空格绑定，而是UGUI上有“空格”触发的东东。
原理跟浏览器里按TAB，然后回车可能会乱触发一样。

**Comment by easternDay** [comment]
可以把OnGUI函数添加射线检测吗，目前的控制台会穿透过去到游戏物体上或者到UI上。

**Comment by MephistoSatanDevil** [comment]
问题依然存在，但是未能找到必定复现的方式。
目前尝试的结果是在乘船靠岸后在地图上走两步并保证上船按钮未消失的情况下多次按空格键有较大机率复现。

**Comment by 0kk470** [comment]
这个问题有可能是由于Unity的StandaloneInputModule默认将空格以及回车作为了Submit事件的输入按键（类似手柄的确认取消按键）而导致的。
按下对应键位后EventSystem会向上一次选择过、实现了ISubmitHandler接口并且处于Active状态的UI对象发送一次事件。

比如我在对话前打开过左侧控制台，EventSytem会将这个开关按钮作为当前选中的UI对象。
![image](https://user-images.githubusercontent.com/25216715/185639761-0045d54d-99fa-4668-8e3e-4b208292f170.png)

然后按空格过对话的同时也会去Invoke这个按钮的回调：
![anim2](https://user-images.githubusercontent.com/25216715/185643172-325ff09b-b1c5-40d3-a8bf-af768169be1f.gif)


解决办法就是在ProjectSettings -> InputManager的设置里将Submit映射的按键置空就行。

**Comment by qige2016** [comment]
> 这个问题有可能是由于Unity的StandaloneInputModule默认将空格以及回车作为了Submit事件的输入按键（类似手柄的确认取消按键）而导致的。 按下对应键位后EventSystem会向上一次选择过、实现了ISubmitHandler接口并且处于Active状态的UI对象发送一次事件。
> 
> 比如我在对话前打开过左侧控制台，EventSytem会将这个开关按钮作为当前选中的UI对象。 ![image](https://user-images.githubusercontent.com/25216715/185639761-0045d54d-99fa-4668-8e3e-4b208292f170.png)
> 
> 然后按空格过对话的同时也会去Invoke这个按钮的回调： ![anim2](https://user-images.githubusercontent.com/25216715/185643172-325ff09b-b1c5-40d3-a8bf-af768169be1f.gif) [ ![anim2](https://user-images.githubusercontent.com/25216715/185643172-325ff09b-b1c5-40d3-a8bf-af768169be1f.gif) ](https://user-images.githubusercontent.com/25216715/185643172-325ff09b-b1c5-40d3-a8bf-af768169be1f.gif) [ ](https://user-images.githubusercontent.com/25216715/185643172-325ff09b-b1c5-40d3-a8bf-af768169be1f.gif)
> 
> 解决办法就是在ProjectSettings -> InputManager的设置里将Submit映射的按键置空就行。

等你提pr

**Comment by 0kk470** [comment]
暂时先把Submit绑定的空格回车键置空了，那这么做的话估计之后就不会用到Unity自带的UI Navigation了。
