### ISSUE TITLE
未带程英的情况下黑龙潭能够自动寻路过去

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#641]
无程英时，这里不应该能自动寻路过去。否则程英在游戏中的唯一作用也就没有了。

**Comment by paulwind** [comment]
当初玩原版时都是自己摸着路进去，程英确实是没有作用...这个也算原汁原味的重制了

**Comment by MephistoSatanDevil** [comment]
> 当初玩原版时都是自己摸着路进去，程英确实是没有作用...这个也算原汁原味的重制了

自己摸着进去和鼠标一点自动寻路过去还是有区别的。

**Comment by yujingsuifeng** [comment]
这个还是不要原汁原味了吧，目前的鼠标自动寻路对游玩体验还是超有帮助的。

**Comment by MephistoSatanDevil** [comment]
> 这个还是不要原汁原味了吧，目前的鼠标自动寻路对游玩体验还是超有帮助的。

只是应该在没有程英的时候的黑龙潭自动寻路路径去掉。否则程英这个队友就彻底失去意义了。
