### ISSUE TITLE
物品信息中，医书、暗器秘籍的“练出物品需经验”项目不应显示

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#651]
物品信息中，医术、暗器秘笈的“练出物品需经验”项不应显示，此值只是系统基础值，实际需要经验和资质还相关。
另外秘笈中使用需求中的资质等是否需要显示有待商榷。因为资质本是隐藏属性。

**Comment by qige2016** [comment]
资质属性不应显示
