### ISSUE TITLE
大地图需要优化或推翻重制

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#652]
大地图目前过挤，场景缩略显示在大地图上辨识度差，大小比例也不合适，方向不对。部分地区，例如雪山派附近行走困难。
目前大地图体验很差，很难有原版行走大地图的流畅感，导致玩家宁可出BUG也要用传送。从游戏成品角度考虑，还是应当优化或重做。
另外，考虑到后续MOD开发，最好能够有相对简单方便的大地图编辑和扩展方式。

**Comment by cgb-usc** [comment]
大地图确实需要重构。太过拥挤，非常不舒服

**Comment by yujingsuifeng** [comment]
非常同意，目前地图偏小，人物移动的格子较大。MOD里面离不开放风筝式的战斗，放风筝需要足够的空间，故而，不仅是大地图，而且战斗场景也都需要优化。

**Comment by tomatostudio** [comment]
可以考虑把地图再做大一些，阻挡的树木、山丘做稀疏或者少一些。否则移动距离虽近，但走动并不方便。

**Comment by chenggongchina** [comment]
考虑找个外包付费解决

**Comment by chenggongchina** [comment]
已解决
