### ISSUE TITLE
面攻击招式攻击范围错误

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#659]
面攻击招式伤害范围错误，现在是菱形♦，应该是方形■。（十级九阳或独孤九剑可看出） #645

如附图：十级九阳神功原版攻击范围为图中上方表示，目前游戏中实际表现为下方区域。

![QQ图片20211206011528](https://user-images.githubusercontent.com/1319061/144756470-11860954-c4dc-427a-8d5d-2a0413d177d3.png)

**Comment by chenggongchina** [comment]
修复
