### ISSUE TITLE
光明圣火阵添加的武功招式和hp没有效果

### ISSUE THREAD

**Issue by Jacky-fe** [jynew/jynew#660]
SetOneMagic(10, 0, 10, 900);
    SetOneMagic(11, 0, 50, 900);
    SetOneMagic(12, 0, 9, 900);
    SetOneMagic(13, 0, 6, 900);
    SetOneMagic(13, 1, 92, 900);
    SetOneMagic(14, 0, 8, 900);
    SetOneMagic(15, 0, 85, 900);
    AddHp(10, 200);
    AddHp(11, 200);
    AddHp(12, 200);
    AddHp(13, 200);
    AddHp(14, 200);
    AddHp(15, 200);

但看起来这几个人hp还是没有变化

**Comment by qige2016** [comment]
战斗UI刷新有点问题
