### ISSUE TITLE
大地图药王庄穿模

### ISSUE THREAD

**Issue by rtsbtx** [jynew/jynew#662]
大地图药王庄穿模

**Comment by qige2016** [comment]
亲，能否附图说明

**Comment by rtsbtx** [comment]
![1640077795(1)](https://user-images.githubusercontent.com/1829123/146909284-cdc3be6d-b8b5-4a5f-bc8a-b82b3e76f3b9.png)

**Comment by rtsbtx** [comment]
> 亲，能否附图说明
![1640077795(1)](https://user-images.githubusercontent.com/1829123/146909448-ee4a3716-4d4b-4d2b-8282-de03c00037f2.png)
