### ISSUE TITLE
经验获取疑似有问题

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#666]
![image](https://user-images.githubusercontent.com/7448857/144976817-73ce830b-6cfe-4b1d-a613-6fc895952c5a.png)
![image](https://user-images.githubusercontent.com/7448857/144976827-2ed816ec-5da8-40f5-8136-cca1658555d1.png)
![image](https://user-images.githubusercontent.com/7448857/144976835-68e78be4-4287-4201-8626-a1bb7727156d.png)

**Comment by MephistoSatanDevil** [comment]
网友实测，原版，武学常识对经验获得无加成。
有加成的疑似MOD版本。
