### ISSUE TITLE
从b站过来的的玩家，不懂编程，用的steam,发现两个问题。

### ISSUE THREAD

**Issue by zeroxyz61** [jynew/jynew#669]
修炼神木王鼎和含沙射影两门武功后，攻击却没有毒性。
不懂编程，望大神改进。
另求如何用指令学习武功和加入队友！

**Comment by qige2016** [comment]
#570 已修
指令查看[wiki](https://github.com/jynew/jynew/wiki/%E6%B8%B8%E6%88%8F%E4%BA%8B%E4%BB%B6%E6%8C%87%E4%BB%A4)
