### ISSUE TITLE
安卓版新游戏加载89%不动了

### ISSUE THREAD

**Issue by qianjun1985** [jynew/jynew#677]
安卓运行新游戏加载，先是74%，然后89%一直不动了，背景音乐一直在。退出重新进入还是老样子。

**Comment by qianjun1985** [comment]
> 附带版本和存档

20211130版，荣耀V10，用mt管理器给apk添加V2签名后安装运行。属性满意确定，载入中……89%，屏幕全黑只有音乐。

**Comment by chenggongchina** [comment]
试一下最新版本是否可以？

**Comment by qianjun1985** [comment]
> 试一下最新版本是否可以？

新版本运行成功
