### ISSUE TITLE
【逻辑错误】AIManager.cs 第701行 会除以0

### ISSUE THREAD

**Issue by LvToDi** [jynew/jynew#685]
int a = (int)Math.Ceiling((double)r2.Hurt / 33);//这里a可能=4
int v = (anqi.AddHp / (4 - a) - UnityEngine.Random.Range(0, 5) - r1.Anqi * 2) / 3;

**Comment by LvToDi** [comment]
这是在游戏运行中报的错，用hurt=100可以复现

**Comment by qige2016** [comment]
hurt=0确实有问题
