### ISSUE TITLE
战斗中死亡的角色没有获得经验

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#696]
原版战斗中死亡的角色是可以获得经验的。

经验的获取算法可能还需要调整，包括战斗中是否做出有效行动（伤害、医疗、用毒、解毒）等对获取的经验加成。

**Comment by qige2016** [comment]
![image](https://user-images.githubusercontent.com/18051955/145742154-b4db6ef5-1b80-4ad4-90d6-ac1756e0a75b.png)
活着才有经验；
战斗做出有效行动（伤害、医疗、用毒、解毒）目前有相应加成。
