### ISSUE TITLE
安卓手机界面按钮及文字太小，不方便操作

### ISSUE THREAD

**Issue by beginor** [jynew/jynew#697]
如题，安卓手机界面上的按钮和文字有点儿小，特别是按钮，用手很难点到。 不清楚Unity的控件是怎么设置的，有没有类似浏览器的响应式布局的方案呢？

**Comment by chenggongchina** [comment]
具体哪个界面？因为我用安卓似乎没遇到点不到的问题。。

**Comment by beginor** [comment]
手机比较旧，屏幕只有5.2寸1080p，点击右上角三个按钮出现的界面，点击左上角出现的下拉列表，都很难选中

**Comment by chenggongchina** [comment]
已经添加，调整分辨率看是否可以、》
