### ISSUE TITLE
一些细节问题

### ISSUE THREAD

**Issue by paulwind** [jynew/jynew#698]
B站过来的，头一次注册，不知道提交的对不对。
1.万鳄岛最左边那排石头中间有障碍走不过去，必须绕行；
2.收武林大会邀请后，队内队友消失，但其他队友还可招募（武林大会和最终战都不可上场），基本没有实质影响；
3.恒山、嵩山战斗地图中间的香炉没有显示，但是无法移动过去，还会阻挡直线输出技能（没有前期存档，过招左冷禅截了个嵩山的图）；
4.以下两项没图：黑木崖打完东方不败后出不去屋（仅限于东方不败战后，不是完全出不去，但会明显被阻挡，要反复试才能出去，推测是和五岳剑派上黑木崖剧情有关，剧情战后再进出屋完全正常）；
5.攻击时经常出现先扣血后出招的动画bug（不影响实际效果，但假如攻击后就是对方行动，会出现招式动画还没出来对面就动起来了）
![万鳄岛](https://user-images.githubusercontent.com/95993499/145700864-6d3a5d30-0cb7-4263-9f66-7d82f158ee26.jpg)
![队友](https://user-images.githubusercontent.com/95993499/145700867-afcacbc1-953f-4909-892f-6849d9e8c2d5.jpg)
![嵩山](https://user-images.githubusercontent.com/95993499/145700906-007dcdc2-32e6-4e45-9f5f-fadc38750bec.jpg)

**Comment by MephistoSatanDevil** [comment]
![QQ截图20211212162656](https://user-images.githubusercontent.com/1319061/145705618-d41bd817-ad79-49b6-b825-ddff8e6c013e.png)
获得武林帖后执行的离队可能少做了一步操作。

**Comment by qige2016** [comment]
第二个问题：需要在角色配置中加当前所在场景属性和入队事件属性，改动较大，先不动
