### ISSUE TITLE
大地图上场景触发入口和建筑位置不吻合

### ISSUE THREAD

**Issue by eaphone** [jynew/jynew#7]
例如，梅庄，其他待更新
![image](https://user-images.githubusercontent.com/22126740/119213421-73f12400-baf1-11eb-9895-fea61f8ab968.png)

期待结果：场景触发入口调整到建筑入口或附近
![image](https://user-images.githubusercontent.com/22126740/119213442-a4d15900-baf1-11eb-842a-def4b15c4c63.png)

**Comment by eaphone** [comment]
修改中

**Comment by eaphone** [comment]
已修改

**Comment by chenggongchina** [comment]
修改后建议增加上pull request的编号

**Comment by eaphone** [comment]
后续每个场景单独优化
