### ISSUE TITLE
离开场景时需要触发的事件会在离开前生效

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#700]
只要在场景出口处，离开按钮出现时就会直接生效了。
这类触发事件的触发时机是否考虑修改为“离开场景回到大地图时”触发？
涉及的事件有百花谷出现蜂箱、辟邪剑法相关事件等。
如果修改了触发时机，可能场景内直接传送会引发的错误会一并修复。

**Comment by qige2016** [comment]
这类触发事件和离开场景无关，属于独立的触发器。只是恰巧放在离开的位置上
