### ISSUE TITLE
找到紫杉龙王后无法进行光明圣火阵

### ISSUE THREAD

**Issue by zergpest** [jynew/jynew#703]
找到紫杉龙王后 回到光明顶 无法打光明圣火阵
![Screenshot_20211213_105141_com jynew jynew](https://user-images.githubusercontent.com/48006366/145745709-2741d37e-bac2-4dc1-9ff6-375f4b9efc8a.jpg)
![Screenshot_20211213_105152_com jynew jynew](https://user-images.githubusercontent.com/48006366/145745715-d0ef279f-4a07-4b97-964f-152fd578054f.jpg)

**Comment by MephistoSatanDevil** [comment]
你是不是用了传送？

**Comment by zergpest** [comment]
没有呀 开船去的
