### ISSUE TITLE
没有装武功秘笈的武功无法升级，像是野球拳、普通攻击

### ISSUE THREAD

**Issue by Brownogc** [jynew/jynew#713]
最新版本的每次战斗，像是金轮寺的番僧，打到后面人物都会叠在一起，应该说人物都跑位了，另外还有一个问题就是，为什麽没有装武功秘笈的武功，像是野球拳、普通攻击這種，我怎麽打都不会升级，我人物都升了快10级以上，请问是哪边出了问题，谢谢。

**Comment by MephistoSatanDevil** [comment]
> 最新版本的每次战斗，像是金轮寺的番僧，打到后面人物都会叠在一起，应该说人物都跑位了，另外还有一个问题就是，为什麽没有装武功秘笈的武功，像是野球拳、普通攻击這種，我怎麽打都不会升级，我人物都升了快10级以上，请问是哪边出了问题，谢谢。

没有秘笈的武功要反复使用才会升级。熟能生巧。平均大概用约六十多次会升一级。

**Comment by Brownogc** [comment]
我照你的话，我一个人打，狂放野球拳70次，等级也升到了16级，但野球拳还是1等，不见升级。

[https://imgur.com/MpDiPxM](url)

**Comment by MephistoSatanDevil** [comment]
> 我照你的话，我一个人打，狂放野球拳70次，等级也升到了16级，但野球拳还是1等，不见升级。
> 
> https://imgur.com/MpDiPxM

再多试试。平均六十多次，也有可能会更高。

**Comment by Brownogc** [comment]
想顺便问一下，武林大会打到何太冲会卡死，连同圣堂裡的十大恶人也会卡死，应该是何太冲的关係，因为十大善人没问题，请问该怎麽解？

**Comment by qige2016** [comment]
> 想顺便问一下，武林大会打其他人正常，但打到何太冲会卡死，连同圣堂裡的十大恶人也会卡死，应该是何太冲的关係，因为十大善人没问题，请问该怎麽解？

版本号多少

**Comment by Brownogc** [comment]
没版本号，我是刚下载这边的档案，然后再自行打包的，所以是最新的。

连结是图
https://imgur.com/Dh7Rf3L
https://imgur.com/dol5O8s
