### ISSUE TITLE
建议优化出场限制

### ISSUE THREAD

**Issue by jardenliu** [jynew/jynew#720]
可以优化一下，一些情况下必须出场的机制吗？
例如找周伯通，金花婆婆练级的时候，主角都学满了，还要必须出场，太影响效率了

**Comment by MephistoSatanDevil** [comment]
原版就是这样

**Comment by jardenliu** [comment]
有没有这样一种可能，原版不合理的地方也可以改掉

**Comment by MephistoSatanDevil** [comment]
> 有没有这样一种可能，原版不合理的地方也可以改掉

原版不合理的地方有很多，计划是放到后面做个MOD统一改掉。
比如小龙女资质太低、比如九阳神功不需要拳掌反而九阴真经要求拳掌、比如狄云不会躺尸剑法反而林平之莫名其妙的会而且躺尸剑法10级攻击力畸高、比如谢逊会的是九阳神功而不是狮子吼
