### ISSUE TITLE
发现一个战斗卡死的bug

### ISSUE THREAD

**Issue by lk119lee** [jynew/jynew#725]
对战闫基时，段誉被打死时仍有出六脉神剑方向，点了方向后，卡死
![新建位图图像](https://user-images.githubusercontent.com/96465948/146891156-65996ae5-1e02-4aa7-88c0-131d929e96ff.jpg)
。

**Comment by MephistoSatanDevil** [comment]
这个是你自己编译的版本？还是从哪里下载的？

**Comment by qige2016** [comment]
应该是我的锅，晚上看下

**Comment by lk119lee** [comment]
steam上的

**Comment by jardenliu** [comment]
20号的版本确实有问题，生命值低于0以后直接卡死
