### ISSUE TITLE
希望可以优化下全屏

### ISSUE THREAD

**Issue by LXTV587** [jynew/jynew#731]
![Screenshot_20211222-010539966](https://user-images.githubusercontent.com/96492103/146972344-a7e0693c-b446-4ee0-b0c5-8a7e9f499fea.jpg)
都出屏幕了

**Comment by LXTV587** [comment]
还有个问题，资质不显示。所以啥武功能学不知道。只能一个个试

**Comment by LXTV587** [comment]
大地图走路有山卡着，路不通。地图是不是还没做完

**Comment by LXTV587** [comment]
![Uploading Screenshot_20211222-012921583.jpg…]()

**Comment by umud66** [comment]
方便提供下手机型号吗 @LXTV587

**Comment by LXTV587** [comment]
Rog3

**Comment by qige2016** [comment]
#747
