### ISSUE TITLE
恒山派内战斗地图bug

### ISSUE THREAD

**Issue by lk119lee** [jynew/jynew#733]
有个地方六脉神剑无法打到，如图
![新建位图图像](https://user-images.githubusercontent.com/96465948/147024900-104dd9d5-df55-4e03-8736-5ad4831bdd21.jpg)

**Comment by lk119lee** [comment]
也无法移动到这个区域，是不是有个什么东西贴图里面没显示出来

**Comment by nixgnod** [comment]
应该原版中有个大炼丹炉？

**Comment by qige2016** [comment]
和打包有关
