### ISSUE TITLE
12月20日的游戏版本，含沙射影修炼成功后，攻击带毒失效

### ISSUE THREAD

**Issue by LeonDLee** [jynew/jynew#738]
12月20日的游戏版本，含沙射影修炼成功后，用武学攻击带毒失效，上一个版本并不存在这个问题。

**Comment by qige2016** [comment]
查证无误

**Comment by qige2016** [comment]
中毒程度＝武功等级×武功中毒点数＋人物攻击带毒
if 敌人抗毒> 中毒程度 或 敌人抗毒> 90 则不中毒
敌人中毒=敌人已中毒＋ 中毒程度/15
if 敌人中毒> 100 then 敌人中毒 ＝100
if 敌人中毒<0 then 敌人中毒=0

附上攻击中毒公式
