### ISSUE TITLE
【重要】根据角色模型管理器 装配所有模型的武器挂点

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#75]
参考方法：[链接](https://github.com/jynew/jynew/wiki/2.5%E8%A7%92%E8%89%B2%E6%A8%A1%E5%9E%8B%E9%85%8D%E7%BD%AE%E7%AE%A1%E7%90%86%E5%99%A8)

对应文件列表：[链接](https://github.com/jynew/jynew/tree/main/jyx2/Assets/BuildSource/Jyx2RoleModelAssets)

可以在[SkillEditor](https://github.com/jynew/jynew/wiki/2.1%E6%8A%80%E8%83%BD%E7%BC%96%E8%BE%91%E5%99%A8)中对结果进行测试。

已完成的请在留言中回复

**Comment by windleer** [comment]
一灯，丁春秋，丐帮弟子，丹青生，张无忌模型武器挂点装配中
