### ISSUE TITLE
安卓版20211227界面严重变形

### ISSUE THREAD

**Issue by beginor** [jynew/jynew#766]
![Screenshot_20211229-191028882](https://user-images.githubusercontent.com/159065/147658482-8e87c50a-c457-4bad-be99-e847a84e1d34.jpg)

![Screenshot_20211229-191225581](https://user-images.githubusercontent.com/159065/147658498-b1a5867f-3dd2-4be9-8bd6-bb8c95c87201.jpg)

![Screenshot_20211229-191236205](https://user-images.githubusercontent.com/159065/147658516-25720862-5b4f-4c2d-b073-aa11ae1b2572.jpg)

![Screenshot_20211229-191308780](https://user-images.githubusercontent.com/159065/147658539-cf064ceb-1d89-4ca8-ae9a-a158e8453304.jpg)

**Comment by 36238** [comment]
我也是一样
