### ISSUE TITLE
战斗结算界面的角色升级提醒应简化

### ISSUE THREAD

**Issue by MephistoSatanDevil** [jynew/jynew#770]
当战斗结算时，一个角色升了多级时，只提醒一次“XXX升级了”，而不应该提示那么多次“XXX升级到N级”

**Comment by LXTV587** [comment]
不不不，原版还有属性加成提醒。现在游戏目前还没有

**Comment by MephistoSatanDevil** [comment]
> 不不不，原版还有属性加成提醒。现在游戏目前还没有

我印象中原版没有，测试的也没有，你确定你说的是“原版”？
