### ISSUE TITLE
1227版本出现战斗卡死bug

### ISSUE THREAD

**Issue by lk119lee** [jynew/jynew#773]
改了人物属性，9级独孤九剑+8级一阳指，打死林平之后他还能继续跑，然后就卡死了。可以选择武功或者物品但是没效果。
![111](https://user-images.githubusercontent.com/96465948/147797695-39a12251-4bf4-484b-9e8f-aed18b0047da.jpg)
![222](https://user-images.githubusercontent.com/96465948/147797706-8ce0c93b-7313-4fc5-a89f-b97ddb878c64.jpg)

**Comment by qige2016** [comment]
看样子是长度超了
