### ISSUE TITLE
不给杨过断肠草解毒，直接去绝情谷底找小龙女。使得后续周伯通、瑛姑剧情无法完成。

### ISSUE THREAD

**Issue by dustier** [jynew/jynew#788]
不给杨过断肠草解毒，直接去绝情谷底找小龙女。过后只能直接去古墓找他们，断肠草无法使用，也就无法得到蜂王浆，使得后续周伯通、瑛姑等相关剧情都无法触发。

**Comment by MephistoSatanDevil** [comment]
> 不给杨过断肠草解毒，直接去绝情谷底找小龙女。过后只能直接去古墓找他们，断肠草无法使用，也就无法得到蜂王浆，使得后续周伯通、瑛姑等相关剧情都无法触发。

不要用传送功能。

**Comment by dustier** [comment]
> > 不给杨过断肠草解毒，直接去绝情谷底找小龙女。过后只能直接去古墓找他们，断肠草无法使用，也就无法得到蜂王浆，使得后续周伯通、瑛姑等相关剧情都无法触发。
> 
> 不要用传送功能。

没有用传送功能，直接开船去的谷底

**Comment by MephistoSatanDevil** [comment]
> > > 不给杨过断肠草解毒，直接去绝情谷底找小龙女。过后只能直接去古墓找他们，断肠草无法使用，也就无法得到蜂王浆，使得后续周伯通、瑛姑等相关剧情都无法触发。
> > 
> > 
> > 不要用传送功能。
> 
> 没有用传送功能，直接开船去的谷底

已经见过杨过的情况下？

**Comment by dustier** [comment]
> > > > 不给杨过断肠草解毒，直接去绝情谷底找小龙女。过后只能直接去古墓找他们，断肠草无法使用，也就无法得到蜂王浆，使得后续周伯通、瑛姑等相关剧情都无法触发。
> > > 
> > > 
> > > 不要用传送功能。
> > 
> > 
> > 没有用传送功能，直接开船去的谷底
> 
> 已经见过杨过的情况下？

是的，流程就是去山洞打蟒蛇、见杨过；直接去谷底见小龙女，然后杨过、小龙女就在古墓了。这时去古墓可以招募他们俩，但再去绝情谷拿断肠草就永远用不出去了，也就没有蜂王浆、以及后续周伯通、瑛姑剧情。
