### ISSUE TITLE
Mac OS 20211223 打完铁掌山小兵后保存卡死，游戏程序未响应

### ISSUE THREAD

**Issue by leo100m** [jynew/jynew#793]
多次测试，打完铁掌山门口小弟后游戏进度保存不了。进入保存界面，点保存就会卡死不响应，无论是覆盖已有存档还是新存档。打之前保存游戏进度没问题。卸载后重新解压游戏，新开档也一样。

队伍：主角+张无忌（队伍此2人，上战场此2人）
设备：MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
系统：Mac os 12.0.1 (21A559)
游戏来源：OS 20211223 https://pan.baidu.com/s/1jkYWtgmWm5rXvebSm1yzpw  提取码:svlt 中的mac版

感谢让广大玩金庸的兄弟们爷青回，好人一生肾好！

![WechatIMG541](https://user-images.githubusercontent.com/97149384/148171208-7358d7ea-7e05-4ac6-ad99-c9cbc899ca48.png)
![WechatIMG543](https://user-images.githubusercontent.com/97149384/148171206-09a07dbb-5e65-4463-9cca-24fa2c2a43df.png)
![WechatIMG544](https://user-images.githubusercontent.com/97149384/148171201-0748c9c6-fe69-44d7-ab7c-3631c2c1ccd9.png)
![WechatIMG546](https://user-images.githubusercontent.com/97149384/148171191-fd0eb9a8-e083-4e80-84a6-eb9ea6c3e2c6.jpeg)
![WechatIMG545](https://user-images.githubusercontent.com/97149384/148171197-76208727-a559-4161-8e41-294874dba963.png)

**Comment by acc972** [comment]
😄

**Comment by qige2016** [comment]
#755 12月27号已修

**Comment by leo100m** [comment]
更新个mac OS的包呗
