### ISSUE TITLE
丐帮入口战斗，丐帮弟子的动作绑定初始化有问题

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#794]
![image](https://user-images.githubusercontent.com/7448857/148398346-891d10f6-ff92-4031-99dd-d4b0760eb2fe.png)

HybridAnimancer初始化的时候没有挂上

**Comment by qige2016** [comment]
#811 可能和这个一样，场景里面的东西没加载完成就进入了场景？

**Comment by qige2016** [comment]
异步加载模型的问题
