### ISSUE TITLE
安卓版，体力低于20后，在战斗中卡死现象

### ISSUE THREAD

**Issue by bordxu** [jynew/jynew#797]
下载的是安卓版，版本号20211106，出现问题描述：当主角体力低于20，在战斗界面，一旦移动到某处后，则会卡死，点击任何无效，只能通过调试界面，瞬移到其他地方，脱离战斗模式，方可存盘，但依旧无法移动及操作。重新读档也不能移动，必须退出游戏才能恢复，估计是与体力值有关。目前出现过的场景有“福威镖局”战林平之，“灵蛇岛”战金花婆婆。都是为了练级或练武功的时候，把体力用到20以下出现的该状况。如图：
![151641549795_ pic](https://user-images.githubusercontent.com/49542743/148528754-5fe42165-96ef-47ae-aba0-66103b840151.jpg)
![161641550010_ pic](https://user-images.githubusercontent.com/49542743/148528780-66f93148-2fcc-4907-9aba-7c916ec807bc.jpg)

**Comment by qige2016** [comment]
#504
