### ISSUE TITLE
更新了「修复资源找不到的问题」，一样无法进入游戏

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#800]
我更新了「修复资源找不到的问题」，但打包之后执行游戏已修復卡在载入中的情况，可还是没有修復问题，因为点击「重新开始」、「载入游戏」本来会有载入中，但变成卡在黑画面，并没有载入中，就卡在那裡，没有进入游戏。

**Comment by qige2016** [comment]
#803 
#804
