### ISSUE TITLE
可以添加IOS版本吗？

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#807]
是否可以添加IOS版本，支援IPad/IPhone手机，并且能够打包成IPA，谢谢。

**Comment by Brown1206** [comment]
我知道可以自行打包，但我只看到Windows、Android、MacOs，想说看能不能帮忙写个编码，让我可以一键打包，谢谢。

**Comment by chenggongchina** [comment]
IOS需要走xcode打包，比较麻烦。一般不会有人愿意去做这个。。

**Comment by Brown1206** [comment]
好的，希望有机会可以添加IOS版，那这样可以删除了，谢谢。
