### ISSUE TITLE
安卓UI被裁剪

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#808]
![070CD2726938C2366CB2574842A38F2D](https://user-images.githubusercontent.com/7448857/149047707-fa307907-116d-4fa5-8a5a-c47d5e1a4d62.jpg)
![1BCA5F61F2FC68B4505F089F725F7F7B](https://user-images.githubusercontent.com/7448857/149047708-d1752ada-5b8d-43e2-bca2-c9be36c4cc50.jpg)

**Comment by jitsmaster** [comment]
Should be fixed now with better ultra wide support
