### ISSUE TITLE
希望能完善PC版对手柄的支持

### ISSUE THREAD

**Issue by zhengcai** [jynew/jynew#809]
经常躺在沙发上连电视用手柄玩，但是发现支持很有限

希望能把手柄的A键(PS手柄的X)映射到space，B键(O)到esc，X键(方块）到x，Y键（三角）到b
然后需要Y/N选择的时候，可以通过A和B键操作

最后战斗的时候，希望能改成右摇杆控制地图的拉扯
而左摇杆和方向键来控制具体的光标位置，这样战斗就可以摆脱鼠标操作了
另外，战斗时选择武功现在也必须鼠标，希望可以改成L1和R1键能够切换当前武功

**Comment by jitsmaster** [comment]
正在加入支持。已经生成 pull request，正在等待 approval。

**Comment by jitsmaster** [comment]
可以试用下列 Fork：
https://github.com/jitsmaster/jynew?organization=jitsmaster&organization=jitsmaster

**Comment by jitsmaster** [comment]
战斗时，左摇杆移动位置，右摇杆控制地图，方向键上下选择其他技能，左右选武功。用方块直接出招，用 X 钮 确认位置或其他技能。

**Comment by jitsmaster** [comment]
缺商店和设定的手柄支持。

**Comment by jitsmaster** [comment]
Merged to main repo

**Comment by qige2016** [comment]
#814 #817 #820
