### ISSUE TITLE
安卓新建游戏， 主角一开始处于自由状态可开箱子与软体娃娃对话等，经过几秒后又突然倒地进入动画。

### ISSUE THREAD

**Issue by ilehe** [jynew/jynew#811]
安卓新建游戏， 主角一开始处于自由状态可开箱子与软体娃娃对话等，经过几秒后又突然倒地进入动画。

**Comment by Brown1206** [comment]
PC也有这个问题，重新开始进入游戏后，不会马上进入动画，是可以自由活动的，但走一下又进入动画，软体娃娃此时才会讲话。

**Comment by MephistoSatanDevil** [comment]
目前确实存在此问题。有的时候新建游戏，软体娃娃的对话事件不会及时触发。

**Comment by qige2016** [comment]
仍有问题
