### ISSUE TITLE
最新版音量跟音效失效了。

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#819]
最新版的调节音量跟音效皆已失效，我尝试调到无声，一样有声音，无法条大小声。

**Comment by birdinforest** [comment]
Hi @Brown1206 我测试了一下，音效和音乐都可以调整音量。见下图
<img width="1285" alt="Screen Shot 2022-01-23 at 3 09 35 pm" src="https://user-images.githubusercontent.com/782895/150664533-fa2ff226-37b1-42fd-af7c-a30eaf0a2998.png">

你那边调整音量时有没有上图的log？是否有报错？如果有的话，麻烦贴上来。

**Comment by Brown1206** [comment]
应该是没问题了，另外想请问，最近更新的MOD管理器是否可以关闭，因为我觉得我用不到，是否可以直接挂载执行就好，不然每次执行游戏还要点击启动实在有点麻烦，希望可以直接挂载，谢谢。

**Comment by birdinforest** [comment]
Hi @Brown1206 你可以开一个新的issue提这个建议。

**Comment by Brown1206** [comment]
那这个问题已经解决，可以删除了，谢谢。
