### ISSUE TITLE
有没有机会自制新角色？

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#825]
有没有机会自制新角色，并且可加入跟战斗，或是新增額外剧情，比方说射雕英雄传的杨康、李莫愁，神雕侠侣的郭襄、霍都、陆无双、公孙止，倚天屠龙记的赵敏、周芷若、小昭，笑傲江湖的任盈盈、岳灵珊、仪琳，这边只是举例而已，最主要是希望加入各个金庸书裡头的新角色，谢谢。

**Comment by qige2016** [comment]
已经提供Mod支持

**Comment by Brown1206** [comment]
我知道有MOD，但我不会做，所以我是问你们团队可不可以做这些新角色。

**Comment by qige2016** [comment]
> 我知道有MOD，但我不会做，所以我是问你们团队可不可以做这些新角色。

目前工作重点还是优化整个框架和提供技术支持

**Comment by MephistoSatanDevil** [comment]
mod的事情交给做MOD的人来做

**Comment by chenggongchina** [comment]
暂时不会投入去做更多的美术资源
