### ISSUE TITLE
打包Android，输出后无法生成Apk。

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#834]
打包Windows没问题，但打包Android最后会出现 gradle build failed，不会生成Apk档，请问可以协助解决吗？谢谢。

**Comment by Brown1206** [comment]
后来我在网上看教学说把有关Gradle的文件全删除，但我再次打包却显示 Gradle install not valid，请问要如何解决，谢谢。

**Comment by qige2016** [comment]
缺少Android sdk吧

**Comment by Brown1206** [comment]
我安装的时候有装Android Build Support套组，这样还是少SDK吗?

**Comment by Brown1206** [comment]
请问要如何解决，谢谢。
[https://imgur.com/a/iOfKXtf](url)
