### ISSUE TITLE
背包菜单在第二次打开后被放大

### ISSUE THREAD

**Issue by tomatostudio** [jynew/jynew#850]
![图片](https://user-images.githubusercontent.com/63195199/152571701-06c56504-f04f-4a82-bee0-849ffad87aec.png)
2020.3.25和26版都试过，都存在这个问题。每次将程序彻底关闭重新打开并加载游戏后，第一次是可以正常显示的。该问题会影响玩家正常使用物品和各种道具，建议修复。

**Comment by qige2016** [comment]
生产包没问题，开发环境可以自己研究下，期待你的pr

**Comment by tomatostudio** [comment]
> 生产包没问题，开发环境可以自己研究下，期待你的pr

已验证，打包后的确没有此问题。我看看是否能修复。

**Comment by firezblade** [comment]
我也遇到这个问题了。。。
可以分享你们用的 android build tools，sdk，oracle java或则openjdk 1.8.0 版本吗？ 谢谢！
我的：-
C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2
C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30
C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK

我打开unity时，unity会自动改：-
jyx2/ProjectSettings/ProjectSettings.asset：-
-  runInBackground: 1
+  runInBackground: 0

-  bundleVersion: 20220203
+  bundleVersion: 20220210
需要改回原版吗？

**Comment by tomatostudio** [comment]
> 我也遇到这个问题了。。。 可以分享你们用的 android build tools，sdk，oracle java或则openjdk 1.8.0 版本吗？ 谢谢！ 我的：- C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2 C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30 C:\Program Files\Unity\Hub\Editor\2020.3.25f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK
> 
> 我打开unity时，unity会自动改：- jyx2/ProjectSettings/ProjectSettings.asset：- -runInBackground: 1 +runInBackground: 0
> 
> -bundleVersion: 20220203 +bundleVersion: 20220210 需要改回原版吗？

我是直接在PC上跑的，2020.3.25f1c1。原则上来说只要能跑就尽量不要修改项目设置，否则别人可能会遇到不可预知的问题。

> 生产包没问题，开发环境可以自己研究下，期待你的pr

尝试Debug了一下，发现是每次打开BagUIPanel和XiaKeUIPanel后，这两者的scale会变成2.2左右，所以就莫名放大了。如果在跑之前选中Maximize On Play的标识，以大屏幕方式跑就没问题。看了下代码，感觉问题不一定在Bag和XiaKe的这两个cs代码中，继续研究熟悉中……

**Comment by qige2016** [comment]
> 目前看下来是需要把BagUIPanel和XiaKeUIPanel的CanvasScaler关闭，可以解决这个问题。类似的其他保存菜单和系统菜单都没有打开这个选项。请大佬看一下这样修改是否会引起别的问题。如果OK的话可以提交PR。
应该不会，测试下生产包就可以提pr了
