### ISSUE TITLE
重新开始进入动画的问题没有修復

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#852]
重新开始进入游戏时，一样没有进入动画，还是可以自由活动，
跑一下才会进入触发动画，要是没动的话就卡在那边，不会进动画。

![123](https://user-images.githubusercontent.com/97239874/152674058-1250e4af-a1cd-4c9e-adb7-1c28fffb8dbf.png)

**Comment by qige2016** [comment]
同#811
