### ISSUE TITLE
MOD管理器是否可以移至设置裡？

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#853]
第一次会跳出这个画面，是否可以把MOD管理器移至设置裡，要使用MOD的人至设置裡开与关，不要用跳出启动框的方式，这样反尔让读取变得更久更卡，PC是不明显，但Android要读取10~20秒上下，跳出启动框之后才会进重新开始的介面，虽然没有MOD之后会跳过，但之后有MOD是不是每次都要启动，这样有点麻烦，谢谢。

**Comment by qige2016** [comment]
目前的MOD设计是开始菜单也可以换掉，原版金庸只作为MOD管理器的默认版本

**Comment by Brown1206** [comment]
请问为什麽我打包后重新开始没触发动画，主角可自由活动，是哪裡有问题，怎麽把我的问题删了呢，谢谢。

**Comment by qige2016** [comment]
> 请问为什麽我打包后重新开始没触发动画，主角可自由活动，是哪裡有问题，怎麽把我的问题删了呢，谢谢。

相同问题我关了

**Comment by Brown1206** [comment]
可是还是有这个问题，并没有解决，
他重新开始游戏还是没办法直接触发动画，要跑一下软体娃娃才会讲话，那这样要怎麽修復。

**Comment by qige2016** [comment]
> 可是还是有这个问题，并没有解决， 他重新开始游戏还是没办法直接触发动画，要跑一下软体娃娃才会讲话，那这样要怎麽修復。

那个问题重新打开了，只保留一个就行

**Comment by Brown1206** [comment]
谢谢你，那這個可以删除了。
