### ISSUE TITLE
五岳合并嵩山一战（进门战斗）自动模式下卡死

### ISSUE THREAD

**Issue by tomatostudio** [jynew/jynew#860]
如图。段誉和令狐冲行动时都发生过。只好退出游戏重来。
![图片](https://user-images.githubusercontent.com/63195199/153765417-34901078-8f68-4c8d-9703-dabd80692563.png)

**Comment by qige2016** [comment]
补充下console的报错

**Comment by tomatostudio** [comment]
> 补充下console的报错

NullReferenceException: Object reference not set to an instance of an object.

MapRole.LookAtBattleBlock (Jyx2.BattleBlockData pos) (at Assets/Scripts/Jyx2GameMap/MapRole.cs:496)
Jyx2.Battle.BattleLoop+<RoleCastSkill>d__9.MoveNext () (at Assets/Scripts/BattleManager/BattleLoop.cs:217)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTask.Factory.cs:205)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
Jyx2.Battle.BattleLoop+<ExecuteAIResult>d__7.MoveNext () (at Assets/Scripts/BattleManager/BattleLoop.cs:165)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTask.Factory.cs:205)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
Jyx2.Battle.BattleLoop+<RoleAIAction>d__6.MoveNext () (at Assets/Scripts/BattleManager/BattleLoop.cs:151)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
Jyx2.Battle.BattleLoop+<StartLoop>d__3.MoveNext () (at Assets/Scripts/BattleManager/BattleLoop.cs:73)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
BattleManager+<StartBattle>d__13.MoveNext () (at Assets/Scripts/BattleManager/BattleManager.cs:141)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
BattleLoader+<InitBattle>d__13.MoveNext () (at Assets/Scripts/BattleLoader.cs:245)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
BattleLoader+<LoadJyx2Battle>d__9.MoveNext () (at Assets/Scripts/BattleLoader.cs:157)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at Assets/Plugins/UniTask/Runtime/UniTask.cs:312)
BattleLoader+<Start>d__6.MoveNext () (at Assets/Scripts/BattleLoader.cs:64)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <0086ce0b9b00409a8713a9c4fe866b9d>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
