### ISSUE TITLE
韦小宝购物车异常

### ISSUE THREAD

**Issue by tomatostudio** [jynew/jynew#868]
![图片](https://user-images.githubusercontent.com/63195199/154100032-fc89565d-4e18-4e40-a94e-e549a3227295.png)
1、天香断续胶描述生命+200，效果显示特殊+200
2、首次与韦小宝交谈时物品库存似乎不正确（忘记截图）
3、购物车无法多品种增加（但首次操作时候底下两个物品是可以同时加购物车的）

**Comment by qige2016** [comment]
#917

**Comment by qige2016** [comment]
3和手柄操作有关，还要想想有没有兼容办法
