### ISSUE TITLE
要怎么修改新技能才能显示出来？

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#870]
可以加入韦小宝的跑步模組吗，想玩韦小宝开局游玩，谢谢。
（不好意思，技能自行研究好了）

**Comment by qige2016** [comment]
跑步动作应该是通用的

**Comment by Brown1206** [comment]
请问要怎么改，跑步模组是哪个？

另外 BABERUTH 这个已经完成，
我就不再开新的，直接在这边給建议，
PC已经可以使用BABERUTH，但是手机没有键盘按钮能按，
所以没办法属性全满，是否可以在左上角那边加入指令，
让手机可以在左上角那边输入 BABERUTH 并且实现属性全满，谢谢。

**Comment by Brown1206** [comment]
跑步已自行解决，
我想把客栈中的韦小宝替换成小虾米该如何做，
又或是我在场景添加小虾米后要如何增加商店事件？

谢谢。

**Comment by Brown1206** [comment]
我尝试写新的Lua对话跟事件，比方说是ka1019，但我测试的时候完全没反应，请问要如何激活写好的Lua?比方说我要让小宝加入跟离队，要如何激活此事件，谢谢。

**Comment by qige2016** [comment]
https://www.bilibili.com/video/BV1mz4y117j3 看下这个合集有没你需要的

**Comment by Brown1206** [comment]
想请教一下，我添加了新的事件，类似张无忌回武当山见太师父的触发事件，写完之后是可以触发的，但事件结束后，接近后又会触发，会一直重复触发，请问要怎麽解决？谢谢。

**Comment by qige2016** [comment]
https://github.com/jynew/jynew/blob/4d417238e41d6109a2670a713b44caecfc2bbd5c/jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs#L102

**Comment by Brown1206** [comment]
我目前弄到瑛姑的线，有解神凋给杨过断肠草，去找绝情谷底找小龙女，又去古墓拿神凋侠侣，也有去百花谷找周伯通给玉峰浆，蜂箱也有出现，然后去找程英加入，再到黑龙潭，有看到瑛姑可是没有出现交互，请问是缺少哪个步骤，还是哪个Lua有问题啊？謝謝

**Comment by Brown1206** [comment]
你好，首先谢谢你一直跟我交流，让我从中学习到很多，但我还是卡关，我照着你给我看的影片操作，但是影片是旧版的教学，但基本上应该是一样的，但旧版的他有配置表可以按，我现在的版本没有影片中的配置表可以按，所以我不确定到底要按什么，我学着操作后，可以帮我看看下图有何错误，我使用神鵰以及华山派弟子想尝试弄一个，但是进到战斗画面，他们手脚无法动弹，连动画都没有，不管我怎么用进战斗画面就是不会动，但是场景中的神鵰就会飞，所以我想请问我是少了什么步骤，最后如果可以的话，是否可以帮忙帮忙，帮我捣鼓一个神鵰华山派弟子的文件档，好让我可以复盖进去使用，我怎么弄都不弄不好，万事拜託，以及谢谢你。
![000](https://user-images.githubusercontent.com/97239874/155857608-4fe5358b-7168-4c39-ab10-aff71d7350f2.png)

![001](https://user-images.githubusercontent.com/97239874/155857615-81828928-c815-4a6d-b555-8b47c4bf82db.png)

**Comment by Brown1206** [comment]
谢谢你一直以来的帮助，让我学了不少，但我有个问题就是为什麽我打包Pc版技能特效可以完全展现，但是Android版的技能打出来的特效，有些是减少甚至变成整个没特效，但PC版却没这个问题，请问这个要怎麽解决啊，谢谢。

**Comment by qige2016** [comment]
一些shader在Android表现不出来，具体哪些可以列一下

**Comment by Brown1206** [comment]
基本上是Hit系列，比方说Hit 1、Hit 2、Hit 3依此类推，像是暗器、黄蓉的打狗棒法有装Hit的特效就是不会显示，那其他武学的特效就是变淡变少，所以Android版的武学特效没办法解决吗？

**Comment by qige2016** [comment]
重新写shader，兼容Android版

**Comment by Brown1206** [comment]
那就拜託你们写兼容Android版的Shader了，等你们更新，谢谢。

**Comment by Brown1206** [comment]
你好，我到了重阳宫打完全真弟子再打丘处机，输了会给七星剑谱，但就没办法再跟丘处机交互，我把道德变坏应该会有第二场，或是我直接变坏，也只有打一场，丘处机说如果我再作恶，下次不饶你，那这样应该会有第二次战斗，一样没办法交互，没办法出发再战全真。

**Comment by Brown1206** [comment]
你好，我想请教一下，我新增了一些关卡，应该是有调在范围内，但是进了关卡之后，却说找不到战斗格子，还有一个问题是我比较想请教的，就是进去之后，我方跟敌方都会离很远，再来人物都挤在一起，请问这个要在哪裡调人物的位置，还有战斗格子的位置是随机的吗，谢谢。

![Screenshot_20220309-034805](https://user-images.githubusercontent.com/97239874/157341360-b3ce459a-ba68-4c09-91f4-8496bf7c1e62.png)

**Comment by Brown1206** [comment]
不好意思，我想请教一下，原本弄得好好的，结果今天要使用技能编辑器却打不开，请问可以帮我看一下是什麽问题吗？要如何解决，谢谢。

![520](https://user-images.githubusercontent.com/97239874/157573319-037da524-1ad4-4004-943f-6a7d245c9194.png)

**Comment by Brown1206** [comment]
想请教一下，原本我圈起来的地方有内力，怎麽突然没有了呢？

![1](https://user-images.githubusercontent.com/97239874/157729101-6f4f47b5-88d8-4f11-abc8-376608616c9f.png)

**Comment by Brown1206** [comment]
想请教一下，请问这是什麽问题，要怎麽解决，谢谢。

![111](https://user-images.githubusercontent.com/97239874/158037847-838d2c87-4843-4054-8631-6112b6055bce.png)
