### ISSUE TITLE
AI人物不行动问题(只能alt+F4强退，丢失存档，极其影响游戏体验)

### ISSUE THREAD

**Issue by millionvoid** [jynew/jynew#878]
遇到了两次，**第一次**是在黑木崖打五岳派，一波输出将敌方杀至只剩岳不群一人，他便不行动
注：
还有两次对照：一个是一波输出将敌方杀至只剩岳不群与左冷禅两人，岳不群仍不行动；一个是一波输出在岳不群身旁剩一个小兵（位于其右侧），岳不群正常行动
**第二次**是武林盟主单挑中，第四波中（波数可能记不清）遇到洪教主（神龙教），它开头便不行动。
以上均有视频为证，如果作者需要，欢迎联系我 jml20@mails.tsinghua.edu.cn

**Comment by qige2016** [comment]
#866
