### ISSUE TITLE
关于左右互搏

### ISSUE THREAD

**Issue by 1211639928** [jynew/jynew#883]
如图我13级时开始修炼左右互搏到了14级左右互搏还是0点经验，同理我给石敢当修炼也是一样，请问这是bug吗？还是游戏设定
![Screenshot_20220219_142519_com jynew jynew](https://user-images.githubusercontent.com/100014021/154789540-5ba1a6d2-ade2-4444-9329-93c81c938a79.jpg)
![Screenshot_20220219_142916_com jynew jynew](https://user-images.githubusercontent.com/100014021/154789543-760b1792-c65e-4183-9e81-66b38f7461b7.jpg)

**Comment by tomatostudio** [comment]
印象中左右互搏不用升级的，练一次练成了就行。如果显示修炼成功后，无左右互搏的效果（同一招式攻击两次），那有可能存在bug。

**Comment by tomatostudio** [comment]
已验证左右互搏练成以后有效果的，让石破天学的。

**Comment by 1211639928** [comment]
谢谢，已更新最新版本，可能是老版本有bug

发自我的iPhone
