### ISSUE TITLE
金花婆婆无法变回紫龙王了

### ISSUE THREAD

**Issue by PoyalPeng** [jynew/jynew#886]
在救回难姑后有对话知道金花婆婆就是紫龙王，但过去找她不会属发，因此拿不到倚天屠龙记了。

**Comment by tomatostudio** [comment]
明教分舵打杨逍成昆->光明顶打六大门派->冰火岛找谢逊给圣火令->成昆居打成昆->冰火岛找谢逊给成昆头颅->光明顶找谢逊->灵蛇岛找金花婆婆。不知道你的流程是怎么样的呢？

**Comment by PoyalPeng** [comment]
就是光明顶找谢逊->去难婆得到金花是紫龙的对话->灵蛇岛找金花婆婆，在这里金花只会和你对话，不会回明教，在上星期的版本还会正常回去的。

**Comment by PoyalPeng** [comment]
问题应该是出在"代码整理（MapRole -> BattleRole和Jyx2Player）"这次的更新中，我试过回复这个更新就正常了，而且有这个更新在skill的动化预览人物的动作不会正常显示，会呆呆站者不动。

**Comment by yomo1989** [comment]
光明顶找谢逊->灵蛇岛找金花婆婆
我也有同样问题，最后找紫衫龙王无法回光明顶 破阵拿倚天屠龙记
版本20220223

**Comment by yomo1989** [comment]
![QQ图片20220227033141](https://user-images.githubusercontent.com/100489956/155856806-6885b68d-f7e7-4482-bc20-a260ad1a0cff.png)
![QQ图片20220227033423](https://user-images.githubusercontent.com/100489956/155856807-467d5f91-c008-4166-9140-bd43333851e3.png)
![QQ图片20220227033431](https://user-images.githubusercontent.com/100489956/155856808-25f7bf6e-6d00-40a2-b87e-eb8b64c97370.png)

**Comment by shandouer** [comment]
我的也是20220223版本，收集13本书后，也是遇到金花婆婆无法被触发激将变回紫衫龙王。。。。 求大神指教！

**Comment by shandouer** [comment]
> 问题应该是出在"代码整理（MapRole -> BattleRole和Jyx2Player）"这次的更新中，我试过回复这个更新就正常了，而且有这个更新在skill的动化预览人物的动作不会正常显示，会呆呆站者不动。 但问题是那个代码我就不知道了，功力不够。

请问您解决这个问题了吗？我下载的是包体，正愁该如何解决。。。
