### ISSUE TITLE
关于游戏的建议

### ISSUE THREAD

**Issue by LXTV587** [jynew/jynew#893]
关于2.23版本
1道具好多描述不准确，而且功能缺少，比如经书要求阴阳属性就没有描述
2战斗没有查看功能(原版有)
3关于箱子未经同意开启要扣道德，也没有显示。
4升级后属性加成未显示
5关于武功尤其毒功，武功带毒最高+5。(原版是根据放毒来的最高可以30毒吧好像)
6关于触发条件，比如捡取硝石，要来回转好久

**Comment by LXTV587** [comment]
7关于功法问题，修炼经验满级之后换功法经验无法继承

**Comment by MephistoSatanDevil** [comment]
1、秘笈阴阳属性本来就没有描述，是根据图片背景进行区别。
3、未经同意扣道德，原版就没有提示
4、升级后属性加成原版就没有显示
7、换秘笈修炼原版就无法继承。你学习语文学到考试能考150分，和你学数学考不及格有什么关系？难道语文学好点，数学就能及格了？

**Comment by supermansaga** [comment]
关于属性加成没显示，我的体验是九阴九阳都没能增加生命值，但葵花宝典可以。虽然没提示要挥刀自宫。
