### ISSUE TITLE
需要制作武器挂点适配方案

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#9]
目前机制 

![F748WQX2 {KO7MBMX} G4JA](https://user-images.githubusercontent.com/7448857/119214017-21663680-baf6-11eb-9174-f549ec646c29.png)

可实现机制为每个角色prefab下单独设置挂点

**Comment by cherubinxxx** [comment]
已经实现并取代原配置表，回头补个文档

**Comment by cherubinxxx** [comment]
![image](https://user-images.githubusercontent.com/6310668/119255036-24dbe980-bbec-11eb-9526-b1e2bf96246e.png)
利用Odin插件写的模型配置管理器，替代原来的模型配置表，并且很方便地配置不同武器的挂载
