### ISSUE TITLE
打完74的丘处机，無法触发75的再战全真。

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#904]
你好，我到了重阳宫打完全真弟子再打74的丘处机，输了会给七星剑谱，我把道德变坏应该会有第二场，点交互完全没反应，应该会触发75的再战全真，道德好的时候丘处机能交互，但道德不好的时候那个交互就没反应，或是我一开始道德不好，输了此时就没办法交互，然后我再去扣道德，一样没办法触发75的再战全真。

**Comment by supermansaga** [comment]
不记得当时道德多少了，但我是被判定为硬闯全真，打赢丘处机后没送七星剑谱。

**Comment by Brown1206** [comment]
道德高打丘处机才会送七星剑谱，道德低打丘处机好像就不会给七星剑谱，目前就是道德低打完丘处机，丘处机就没办法交互了。

**Comment by supermansaga** [comment]
最好能设置成丘处机不服再战，像之前打金轮法王那些小喽啰或者打欧阳克一样。离开场景再入就能再打。
