### ISSUE TITLE
这边的内力消失了。

### ISSUE THREAD

**Issue by Brown1206** [jynew/jynew#907]
这边的内力消失了，似乎是这个问题。 Scripts > Jyx2UIScripts > RoleUIItem.cs

![157729101-6f4f47b5-88d8-4f11-abc8-376608616c9f](https://user-images.githubusercontent.com/97239874/157821271-df4d06b9-5717-4350-89fa-a7bdab613dab.png)

**Comment by Brown1206** [comment]
请问这个可以先更新吗？不然看不到内力有点彆扭。

**Comment by qige2016** [comment]
915b33f6f94cdc18370a3606da017044e9b5d0
