### ISSUE TITLE
生命值和內力值搞反了

### ISSUE THREAD

**Issue by Lo-Shan** [jynew/jynew#918]
1.使用增值道具如潘桃,敘述為加生命但實際加了內力
2.武功如九陽神功,升級時所加的數值也不對,玩到後來內力值很高但血還是薄的

**Comment by qige2016** [comment]
e371d1023e43728e20ca190057bfcab23165900e 错误描述相关已修

**Comment by Lo-Shan** [comment]
阿,那可能玩到舊版本
