### ISSUE TITLE
2022年3月25日版本等待功能不可用

### ISSUE THREAD

**Issue by Robert698** [jynew/jynew#927]
开局与张无忌一起去打胡斐，战斗中间点击等待会在自己队伍这边来回切换无法进入敌人回合

**Comment by qige2016** [comment]
等待不就是放到最后行动吗

**Comment by Robert698** [comment]
等待是放空一个回合，然后在下个回合可以执行两次攻击，在高智商不会左右互博的时候很有用

**Comment by MephistoSatanDevil** [comment]
> 等待是放空一个回合，然后在下个回合可以执行两次攻击，在高智商不会左右互博的时候很有用

不是。
等待是将当前角色的行动顺序排至本回合最末，而不是排到下一回合。

如果你当前角色轻功最高最先行动，选择等待会变成：所有其他角色行动完毕最后该角色才行动，行动完毕后立刻进入下一回合，而因为当前角色最先行动，则该角色继续行动。
因此会让你误以为等待是让角色下回合行动两次。

**Comment by Robert698** [comment]
嗯，从程序设计角度这样解释更清晰，不过3月25日版本的情况是排序的所有其他角色不包含敌方角色，我方两个角色按了等待没有跳到敌方角色那边

**Comment by MephistoSatanDevil** [comment]
> 嗯，从程序设计角度这样解释更清晰，不过3月25日版本的情况是排序的所有其他角色不包含敌方角色，我方两个角色按了等待没有跳到敌方角色那边

目前最新版本0328实测表现正常，你确认一下是不是你这两个角色已经是本回合最后两个需要行动的角色了。

**Comment by Robert698** [comment]
我刚测试了一下0328的版本，还是在最开始，加了段誉，加了张无忌，步行找张三丰那梯云纵，张无忌修炼九阳神功，段誉不练，自己练梯云纵，修改资质AddAptitude(0, 100)，AddAptitude(0, -55)，步行找胡斐，战斗，选张无忌和自己，两次武当长拳把胡斐打到半血，然后张无忌和自己等待，然后就不停的在张无忌和自己这边切换，无法切换到胡斐那边

**Comment by MephistoSatanDevil** [comment]
胡斐行动过了么？

**Comment by Robert698** [comment]
因为是刚开始，所以轻功是胡斐大于张无忌大于自己，胡斐行动过了，在张无忌回合点的等待，又在自己回合点的等待，然后就又切到张无忌回合了，中间没有胡斐的行动，除非启动攻击或休息才能切到胡斐的行动

**Comment by MephistoSatanDevil** [comment]
> 因为是刚开始，所以轻功是胡斐大于张无忌大于自己，胡斐行动过了，在张无忌回合点的等待，又在自己回合点的等待，然后就又切到张无忌回合了，中间没有胡斐的行动，除非启动攻击或休息才能切到胡斐的行动

这个逻辑没错啊？？
行动队列顺序：胡斐、张无忌、主角
回合开始：
1、胡斐行动，剩余队列：张无忌、主角
2、张无忌行动，等待，将张无忌行动顺序排在队列最后（主角之后），剩余队列：主角、张无忌
3、主角行动，等待，则再将主角行动顺序排在当前队列最后（张无忌之后），剩余队列：张无忌、主角

你这种可不就是在主角和张无忌之间来回行动了？又没进行到下一回合，怎么会有胡斐行动？
