### ISSUE TITLE
华山和青城派卡大地图

### ISSUE THREAD

**Issue by chenggongchina** [jynew/jynew#931]
![`WJNL$2W3Z }Z564~U71~LL](https://user-images.githubusercontent.com/7448857/160237345-b969fd61-b3f5-414d-9b08-e7eff36ed991.jpg)

**Comment by chenggongchina** [comment]
https://user-images.githubusercontent.com/7448857/160237488-9dd46fae-ce35-4525-a988-3e7a9fff49e8.mp4

**Comment by qige2016** [comment]
经测试已修复
