### ISSUE TITLE
河洛客栈有bug，胡斐交互不了

### ISSUE THREAD

**Issue by yang-to123** [jynew/jynew#937]
手机版，机型：荣耀v30
问题一：河洛客栈进去画面疯狂抖动，一直拖住方向键一段时间可以卡进去。出来还是一样画面抖动，一直拖动方向键可以勉强出来。
问题二：胡斐居进去，胡斐周围一直绕圈也不出现对话和使用道具的标志，无法交互。

**Comment by qige2016** [comment]
#933
