### ISSUE TITLE
求教安卓游戏存档位置，以及发现的一些影响游戏的小bug。

### ISSUE THREAD

**Issue by nishizhumagu** [jynew/jynew#942]
1、希望作者能告知下安卓的存档位置，便于与pc同步存档
2、希望在人物属性界面显示资质啊
3、在战斗界面，最下面的武功一栏有淡黑色的遮罩，如果想要点击在这个位置的移动方格，是没办法点击的。
4、开启天宁寺剧情后，进入天宁寺不小心点到离开，再进去就无法与其他人交互了，我是退出重新进入游戏存档才解决此问题，如果方便的话麻烦作者重现下确认下是不是bug?
5、安卓希望增加不息屏功能。

**Comment by MephistoSatanDevil** [comment]
原版人物属性界面就不显示资质
