### ISSUE TITLE
人物升级之后 血条不满

### ISSUE THREAD

**Issue by cgb-usc** [jynew/jynew#951]
人物升级之后，血会恢复，但只会恢复到升级之前的血量。应该修改为恢复到升级之后的满血血量

**Comment by MephistoSatanDevil** [comment]
> 人物升级之后，血会恢复，但只会恢复到升级之前的血量。应该修改为恢复到升级之后的满血血量

目前的版本人物升级后血量是恢复到升级后的最大生命值。
你说的是哪个版本？
