### ISSUE TITLE
20220328问题

### ISSUE THREAD

**Issue by LXTV587** [jynew/jynew#964]
![Screenshot_20220408-212851880](https://user-images.githubusercontent.com/96492103/162445544-25399538-4752-467b-a984-cf0f25d6694d.jpg)
更新后船上不了了，而且下载mod后会闪退，不开mod偶尔也会闪退。手机rog3

**Comment by LXTV587** [comment]
rog3

**Comment by MephistoSatanDevil** [comment]
新建个存档看看。因为大地图改过，存档里船的位置可能不在合适的位置。
