### ISSUE TITLE
最新版本没法运行, Window 10

### ISSUE THREAD

**Issue by hckhor88** [jynew/jynew#968]
最新版本没法运行,请问如何解决，谢谢

我用的是GITHUB最新版本，我没改过任何东西,
尝试使用两个unity也无法运行
2020.3.25f1c1
2020.3.23f1c1

![image](https://user-images.githubusercontent.com/103172707/162553584-6711b673-98ea-4264-8d75-73efc29d0346.png)

**Comment by chenggongchina** [comment]
unity自动更新package的时候失败了，尝试重新import unity的manifest

**Comment by hckhor88** [comment]
> 
请问如何重新import? 是重新从github上用github desktop重新下载全部软件也可以对吗？

对了，我们应该用
2020.3.25f1c1 还是
2020.3.23f1c1？
