### ISSUE TITLE
小宝库存1道具无限买

### ISSUE THREAD

**Issue by schen414** [jynew/jynew#978]
版本:20220328

只要不关闭和够钱, 小宝库存1的道具可以无限买
第一次买
![buy1](https://user-images.githubusercontent.com/10465538/163256189-02a5ee09-b403-4bf5-8d53-8ecb8fa21c32.jpg)
无限买
![buy_again](https://user-images.githubusercontent.com/10465538/163256235-1608fa95-7048-4ce4-a015-544c6f50bac0.jpg)

**Comment by qige2016** [comment]
1194404c0cd33f506415f0f57225e3e6d0bc2138
