### ISSUE TITLE
想请教一下。

### ISSUE THREAD

**Issue by Brown1026** [jynew/jynew#987]
想请教一下。

**Comment by Brown1026** [comment]
我把韦小宝弄成可加入角色，
请问那个离队的文本要怎么写，
就是离队后一样可以随机出现在各个客栈中，
因为我写的就是加入后、在离队会变成各个客栈中都有韦小宝，

可以帮忙写个范例让我参考，拜託，谢谢。

**Comment by qige2016** [comment]
这块可以在角色配置的asset里面加入队、离队的事件，所在场景模型的信息，你可以尝试大改下这块

**Comment by qige2016** [comment]
#698 这个问题也可以一并解决

**Comment by qige2016** [comment]
原lua保留，配置新的lua

**Comment by Brown1026** [comment]
你是说保留这个 ↓

Talk(0, "多谢韦小宝相助，有需要再去找你．", "talkname0", 1);
Leave(320);
ModifyEvent(1, 17, 1, 1, 938, -1, -1, -1, -1, -1, 0, -2, -2);
ModifyEvent(3, 15, 1, 1, 938, -1, -1, -1, -1, -1, 0, -2, -2);
ModifyEvent(40, 21, 1, 1, 938, -1, -1, -1, -1, -1, 0, -2, -2);
ModifyEvent(60, 16, 1, 1, 938, -1, -1, -1, -1, -1, 0, -2, -2);
ModifyEvent(61, 11, 1, 1, 938, -1, -1, -1, -1, -1, 0, -2, -2);
jyx2_ReplaceSceneObject("1","Dynamic/韦小宝","1");
jyx2_ReplaceSceneObject("3","Dynamic/韦小宝","1");
jyx2_ReplaceSceneObject("40","Dynamic/韦小宝","1");
jyx2_ReplaceSceneObject("60","Dynamic/韦小宝","1");
jyx2_ReplaceSceneObject("61","Dynamic/韦小宝","1");
do return end;

然后配置写新的Lua吗？

其实我不会写语法，
我是拿前面的Lua来改，
我有在韦小宝的队友离场对话加入事件，
所以才想请你帮我在文本上修改一下，

谢谢啦。
好让韦小宝能够随机出现在客栈当中，

**Comment by qige2016** [comment]
[    public static void TransportWei()](https://github.com/jynew/jynew/blob/25004967678ef96d3c6cfb910721fa3d82e92d06/jyx2/Assets/Scripts/Jyx2Console.cs#L109)
代码在这，需要改在Jyx2LuaBridge里面，再在lua调用

**Comment by Brown1026** [comment]
谢谢你，
基本上我还是不懂要怎么操作，
可以帮我改一下Lua跟Jyx2LuaBridge提供给我吗，

因为我是真的不会写语法。

**Comment by qige2016** [comment]
暂无计划
