### ISSUE TITLE
【Bug】【MacOSX】Mac平台上编辑器中无法启动游戏，报错信息如下

### ISSUE THREAD

**Issue by XINCGer** [jynew/jynew#998]
![屏幕快照 2022-05-03 下午10 57 07](https://user-images.githubusercontent.com/10908565/166478936-55ccdf9f-977c-4f82-bef6-226f157287ed.png)

`UnityEngine.AddressableAssets.InvalidKeyException: Exception of type 'UnityEngine.AddressableAssets.InvalidKeyException' was thrown., Key=System.Collections.Generic.List`1[System.String], Type=Jyx2SkillDisplayAsset
UnityEngine.AddressableAssets.Addressables:LoadAssetsAsync<Jyx2SkillDisplayAsset> (System.Collections.IEnumerable,System.Action`1<Jyx2SkillDisplayAsset>,UnityEngine.AddressableAssets.Addressables/MergeMode)
Jyx2.MOD.MODLoader/<LoadAssets>d__7`1<Jyx2SkillDisplayAsset>:MoveNext () (at Assets/Scripts/MOD/MODLoader.cs:123)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1<System.Collections.Generic.List`1<Jyx2SkillDisplayAsset>>:Start<Jyx2.MOD.MODLoader/<LoadAssets>d__7`1<Jyx2SkillDisplayAsset>> (Jyx2.MOD.MODLoader/<LoadAssets>d__7`1<Jyx2SkillDisplayAsset>&) (at Assets/Plugins/UniTask/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:242)
Jyx2.MOD.MODLoader:LoadAssets<Jyx2SkillDisplayAsset> (System.Collections.Generic.List`1<string>)
Jyx2ResourceHelper/<Init>d__1:MoveNext () (at Assets/Scripts/Jyx2ResourceHelper.cs:76)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Assets/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<System.Collections.Generic.List`1<string>>:TrySetResult (System.Collections.Generic.List`1<string>) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<Jyx2.MOD.MODLoader/<LoadOverrideList>d__10, System.Collections.Generic.List`1<string>>:SetResult (System.Collections.Generic.List`1<string>) (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:328)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1<System.Collections.Generic.List`1<string>>:SetResult (System.Collections.Generic.List`1<string>) (at Assets/Plugins/UniTask/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:201)
Jyx2.MOD.MODLoader/<LoadOverrideList>d__10:MoveNext () (at Assets/Scripts/MOD/MODLoader.cs:182)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<Jyx2.MOD.MODLoader/<LoadOverrideList>d__10, System.Collections.Generic.List`1<string>>:Run () (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Assets/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<UnityEngine.TextAsset>:TrySetResult (UnityEngine.TextAsset) (at Assets/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.AddressablesAsyncExtensions/AsyncOperationHandleConfiguredSource`1<UnityEngine.TextAsset>:Continuation (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1<UnityEngine.TextAsset>) (at Assets/Plugins/UniTask/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:333)
DelegateList`1<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1<UnityEngine.TextAsset>>:Invoke (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1<UnityEngine.TextAsset>) (at Library/PackageCache/com.unity.addressables@1.18.19/Runtime/ResourceManager/Util/DelegateList.cs:69)
UnityEngine.ResourceManagement.Util.DelayedActionManager:LateUpdate () (at Library/PackageCache/com.unity.addressables@1.18.19/Runtime/ResourceManager/Util/DelayedActionManager.cs:159)
`

**Comment by clw5180** [comment]
可以请教下是如何解决的么
